"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {Membership,Organization,Profile,Project} from "../types";

type Context={organization:Organization;membership:Membership;profile:Profile|null;projects:Project[];members:Membership[];profiles:Profile[];session:{user:{id:string}}};
type Props={context:Context;open:boolean;close:()=>void;onSaved:()=>void};

const TYPES=["imagem","vídeo","documento","apresentação","planilha","identidade visual","template","link","outro"];
const STATUS=["rascunho","aprovado","publicado","arquivado"];
const safe=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").toLowerCase();

export function MarketingAssetManagerV63({context,open,close,onSaved}:Props){
 const[campaigns,setCampaigns]=useState<any[]>([]),[assets,setAssets]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{const s=getSupabase();if(!s)return;const org=context.organization.id;const[c,a]=await Promise.all([s.from("marketing_campaigns").select("id,name").eq("organization_id",org).order("name"),s.from("marketing_assets").select("*").eq("organization_id",org).order("created_at",{ascending:false})]);if(c.error||a.error)setError(c.error?.message||a.error?.message||"Não foi possível carregar os ativos.");else{setCampaigns(c.data||[]);setAssets(a.data||[])}},[context.organization.id]);
 useEffect(()=>{if(open)load()},[open,load]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const s=getSupabase();if(!s)throw new Error("Supabase indisponível.");const f=new FormData(e.currentTarget),file=f.get("file") as File,url=String(f.get("public_url")||"").trim();if((!file||!file.size)&&!url)throw new Error("Selecione um arquivo ou informe um link externo.");if(file?.size>50*1024*1024)throw new Error("O arquivo deve ter no máximo 50 MB.");const campaignId=String(f.get("campaign_id")||"")||null;let storagePath:string|null=null;if(file?.size){storagePath=`${context.organization.id}/marketing-assets/${campaignId||"avulsos"}/${Date.now()}-${safe(file.name)}`;const up=await s.storage.from("erp-documents").upload(storagePath,file,{contentType:file.type||"application/octet-stream",upsert:false});if(up.error)throw new Error(up.error.message)}const payload={organization_id:context.organization.id,project_id:String(f.get("project_id")||"")||null,campaign_id:campaignId,name:String(f.get("name")||file?.name||"Ativo de marketing").trim(),asset_type:String(f.get("asset_type")||"documento"),storage_path:storagePath,public_url:url||null,version:Math.max(1,Number(f.get("version")||1)),status:String(f.get("status")||"rascunho"),usage_rights:String(f.get("usage_rights")||"")||null,expires_at:String(f.get("expires_at")||"")||null,tags:String(f.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean),created_by:context.session.user.id,updated_at:new Date().toISOString()};const ins=await s.from("marketing_assets").insert(payload);if(ins.error){if(storagePath)await s.storage.from("erp-documents").remove([storagePath]);throw new Error(ins.error.message)}await load();onSaved();(e.currentTarget as HTMLFormElement).reset()}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar o ativo.")}finally{setBusy(false)}}
 async function openAsset(asset:any){try{if(asset.public_url){window.open(asset.public_url,"_blank","noopener,noreferrer");return}if(!asset.storage_path)throw new Error("Arquivo não localizado.");const s=getSupabase();if(!s)throw new Error("Supabase indisponível.");const r=await s.storage.from("erp-documents").createSignedUrl(asset.storage_path,600);if(r.error||!r.data?.signedUrl)throw new Error(r.error?.message||"Não foi possível abrir o arquivo.");window.open(r.data.signedUrl,"_blank","noopener,noreferrer")}catch(err){setError(err instanceof Error?err.message:"Não foi possível abrir o ativo.")}}
 if(!open)return null;
 return <div className="modal-backdrop asset-manager-backdrop" onMouseDown={close}><section className="modal extra-large marketing-asset-manager-v63" onMouseDown={e=>e.stopPropagation()}><header className="asset-manager-header"><div><small>BIBLIOTECA DE MARKETING</small><h2>Adicionar e gerenciar ativos</h2><p>Arquivos privados, links, versões, direitos de uso e vínculo com campanhas.</p></div><button className="modal-close" onClick={close}>×</button></header>{error&&<div className="feedback error">{error}</div>}<div className="asset-manager-layout"><form onSubmit={submit} className="asset-upload-form"><h3>Novo ativo</h3><div className="form-grid two"><label className="span-2">Nome do ativo<input name="name" placeholder="Ex.: Book comercial Solaris" required/></label><label>Tipo<select name="asset_type">{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select name="status">{STATUS.map(x=><option key={x}>{x}</option>)}</select></label><label>Campanha<select name="campaign_id"><option value="">Avulso / institucional</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Empreendimento<select name="project_id"><option value="">Corporativo</option>{context.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Versão<input name="version" type="number" min="1" defaultValue="1"/></label><label>Validade dos direitos<input name="expires_at" type="date"/></label><label className="span-2">Direitos de uso<input name="usage_rights" placeholder="Ex.: uso institucional por prazo indeterminado"/></label><label className="span-2">Tags<input name="tags" placeholder="solar, book, corretores, lançamento"/></label><label className="span-2 file-drop-v63">Arquivo<input name="file" type="file" accept="image/*,video/*,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.csv,.zip"/><span>PDF, imagem, vídeo, apresentação, planilha ou arquivo compactado · até 50 MB</span></label><label className="span-2">Ou link externo<input name="public_url" type="url" placeholder="https://..."/></label></div><button className="primary wide" disabled={busy}>{busy?"Enviando e cadastrando...":"Adicionar à biblioteca"}</button></form><div className="asset-library-v63"><header><div><h3>Ativos cadastrados</h3><small>{assets.length} item(ns)</small></div></header>{assets.length?<div className="asset-library-list-v63">{assets.map(a=><article key={a.id}><div><strong>{a.name}</strong><small>{a.asset_type} · versão {a.version||1} · {a.status}</small><span>{(a.tags||[]).join(" · ")||"Sem tags"}</span></div><button onClick={()=>openAsset(a)}>Abrir</button></article>)}</div>:<div className="empty">Nenhum ativo cadastrado.</div>}</div></div></section></div>
}
