begin;
set local statement_timeout='120s';
set local lock_timeout='5s';
do $test$
declare org uuid; actor uuid; other_actor uuid; e uuid; other_event uuid; token uuid:=gen_random_uuid(); memory_id uuid; m jsonb; result jsonb; result2 jsonb; refused boolean; n integer; state_hash text:=repeat('a',64);
begin
  select m.organization_id,m.user_id into org,actor from public.organization_members m join public.organizations o on o.id=m.organization_id where m.active and m.role='admin' and o.active order by m.organization_id,m.user_id limit 1;
  select id into other_actor from auth.users where id<>actor order by id limit 1;
  if org is null or other_actor is null then raise exception 'Test needs an active admin and another existing account'; end if;
  perform set_config('request.jwt.claim.sub',actor::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
  if has_table_privilege('authenticated','public.arisa_archive','INSERT,UPDATE,DELETE') or has_table_privilege('authenticated','public.arisa_memories','INSERT,UPDATE,DELETE') or has_table_privilege('authenticated','public.arisa_mail_messages','INSERT,UPDATE,DELETE') then raise exception 'Direct writes exposed'; end if;
  if has_function_privilege('authenticated','public.arisa_mail_service(text,uuid,uuid,jsonb)','EXECUTE') or has_function_privilege('anon','public.arisa_background_secret()','EXECUTE') or has_function_privilege('authenticated','public.arisa_memory_worker(text,jsonb)','EXECUTE') then raise exception 'Private worker exposed'; end if;
  e:=private.arisa_archive_put(org,actor,'qa_test',gen_random_uuid()::text,'chat','message','user','user:'||actor,'QA','QA evidence','Prefiro propostas por e-mail.',jsonb_build_object('password','SECRET MUST NOT SURVIVE','nested',jsonb_build_object('refresh_token','SECRET MUST NOT SURVIVE')),now(),false);
  other_event:=private.arisa_archive_put(org,other_actor,'qa_private',gen_random_uuid()::text,'chat','message','user','user:'||other_actor,'QA','QA other private','Conteúdo privado de outro administrador.','{}',now(),false);
  if (select payload::text like '%SECRET MUST NOT SURVIVE%' from public.arisa_archive where id=e) then raise exception 'Secret was archived'; end if;
  insert into private.arisa_memory_jobs(event_id,status,attempts,lease,lease_until) values(e,'processing',1,token,now()+interval '3 minutes');
  m:=jsonb_build_object('kind','observation','topic','communication','claim','Prefere propostas por e-mail.','evidence','Prefiro propostas por e-mail.','confidence',1,'about_speaker',true);
  result:=public.arisa_memory_worker('finish',jsonb_build_object('event_id',e,'lease',token,'memories',jsonb_build_array(m,m||jsonb_build_object('claim','Evidência inventada.','evidence','Não está na fonte.')),'model','qa-test','usage','{}'::jsonb));
  if (result->>'count')::integer<>1 then raise exception 'Evidence validation failed: %',result; end if;
  select id into memory_id from public.arisa_memories where source_event_id=e and confidence=.75 and expires_at is not null;
  if memory_id is null then raise exception 'Perception confidence/expiry failed'; end if;
  execute 'set local role authenticated';
  select count(*) into n from public.arisa_archive where id in(e,other_event);
  if n<>1 then raise exception 'Private archive RLS failed'; end if;
  result:=public.arisa_archive_search(org,'QA',null,100,0);
  if result->'rows' @> jsonb_build_array(jsonb_build_object('id',other_event)) then raise exception 'Archive search leaked another private conversation'; end if;
  result:=public.arisa_recall(org,'propostas',null,50);
  if not result @> jsonb_build_array(jsonb_build_object('id',memory_id)) then raise exception 'Recall lost authorized memory'; end if;
  perform public.arisa_memory_review(memory_id,'rejected','QA correction, always rolled back');
  result:=public.arisa_recall(org,'propostas',null,50);
  if result @> jsonb_build_array(jsonb_build_object('id',memory_id)) then raise exception 'Rejected perception still recalled'; end if;
  refused:=false;
  begin update public.arisa_archive set content='changed' where id=e; exception when insufficient_privilege then refused:=true; end;
  if not refused then raise exception 'Immutable archive could be changed'; end if;
  execute 'reset role';
  result:=public.arisa_mail_service('status',org,actor);
  if coalesce((result->>'connected')::boolean,false) then raise exception 'Fixture assumes Google not yet connected'; end if;
  perform public.arisa_mail_service('configure',org,actor,jsonb_build_object('client_id','12345-qatest.apps.googleusercontent.com','client_secret','QA_ROLLBACK_FAKE_CLIENT_SECRET'));
  perform public.arisa_mail_service('oauth_begin',org,actor,jsonb_build_object('state_hash',state_hash,'verifier',repeat('q',64)));
  refused:=false;
  begin perform public.arisa_mail_service('oauth_consume',org,other_actor,jsonb_build_object('state_hash',state_hash)); exception when others then refused:=true; end;
  if not refused then raise exception 'OAuth state transferable to another actor'; end if;
  result:=public.arisa_mail_service('oauth_consume',org,actor,jsonb_build_object('state_hash',state_hash));
  if result->>'verifier'<>repeat('q',64) then raise exception 'PKCE verifier unavailable to authorized server'; end if;
  refused:=false;
  begin perform public.arisa_mail_service('oauth_consume',org,actor,jsonb_build_object('state_hash',state_hash)); exception when others then refused:=true; end;
  if not refused then raise exception 'OAuth state replay accepted'; end if;
  result:=public.arisa_mail_service('prepare',org,actor,jsonb_build_object('operation_key',repeat('b',64),'to',jsonb_build_array('qa@example.invalid'),'subject','QA no send','body','Synthetic, rollback only.'));
  result2:=public.arisa_mail_service('prepare',org,actor,jsonb_build_object('operation_key',repeat('b',64),'to',jsonb_build_array('qa@example.invalid'),'subject','QA no send','body','Synthetic, rollback only.'));
  if result->>'id'<>result2->>'id' then raise exception 'Outbox idempotency failed'; end if;
  update public.arisa_mail_messages set status='unknown' where id=(result->>'id')::uuid;
  result2:=public.arisa_mail_service('send_begin',org,actor,jsonb_build_object('id',result->>'id'));
  if (result2->>'send')::boolean is not false then raise exception 'Ambiguous send was retried'; end if;
  if exists(select 1 from public.arisa_archive where payload::text like '%QA_ROLLBACK_FAKE_CLIENT_SECRET%') then raise exception 'OAuth secret exposed in archive'; end if;
  raise notice 'PASS: RLS, archive immutability, redaction, evidence, review, expiry, OAuth binding, replay, outbox idempotency and ambiguous-send protection';
end $test$;
rollback;
