-- All rows and network jobs roll back; this never sends a WhatsApp message.
begin;
set local statement_timeout='120s';
set local lock_timeout='5s';
do $test$
declare org uuid;actor uuid;thread uuid;foreign_thread uuid;request_id uuid:=gen_random_uuid();inbound uuid;job jsonb;result jsonb;op jsonb;refused boolean;phone text:='551197'||lpad(floor(random()*10000000)::bigint::text,7,'0');receiver text:='990000000000098';
begin
  select m.organization_id,m.user_id into org,actor from public.organization_members m join public.organizations o on o.id=m.organization_id where m.active and m.role='admin' and o.active order by m.organization_id,m.user_id limit 1;
  if org is null then raise exception 'Active admin required';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
  if has_function_privilege('anon','public.arisa_whatsapp_monitor(uuid,uuid,text,text,integer,integer)','EXECUTE') or has_function_privilege('anon','public.arisa_whatsapp_inbox(uuid,uuid,text)','EXECUTE') then raise exception 'Anonymous monitor exposed';end if;
  update crm_private.arisa_whatsapp_reply_jobs set available_at=now()+interval '1 day' where status='pending';
  update crm_private.whatsapp_runtime_settings set enabled=false,phone_number_id=receiver where organization_id=org;
  insert into crm_private.arisa_whatsapp_channel(organization_id,enabled,auto_reply_enabled,updated_by,webhook_verified_at) values(org,true,true,actor,now()) on conflict(organization_id) do update set enabled=true,auto_reply_enabled=true,updated_by=actor,webhook_verified_at=now();
  insert into public.arisa_whatsapp_threads(organization_id,phone_number_id,phone,contact_name,created_by,last_inbound_at) values(org,receiver,phone,'Rollback panel fixture',actor,now()) returning id into thread;
  insert into public.arisa_whatsapp_threads(organization_id,phone_number_id,phone,contact_name,created_by) values(org,'990000000000097',phone,'Different channel',actor) returning id into foreign_thread;
  insert into public.arisa_whatsapp_messages(organization_id,thread_id,direction,content,occurred_at,delivery_status) select org,thread,'outbound','History '||g,now()-interval '1 minute'*g,'delivered' from generate_series(1,61) g;
  result=public.arisa_whatsapp_monitor(org,thread,'Rollback panel');
  if result->>'total'<>'1' or result->>'message_total'<>'61' or jsonb_array_length(result->'messages')<>50 or result->'messages'->0->>'content'<>'History 50' or result->'messages'->49->>'content'<>'History 1' then raise exception 'Monitor paging/order mismatch';end if;
  result=public.arisa_whatsapp_monitor(org,thread,'','all',0,50);
  if jsonb_array_length(result->'messages')<>11 then raise exception 'Older history missing';end if;
  refused=false;begin perform public.arisa_whatsapp_monitor(org,foreign_thread);exception when raise_exception then refused=true;end;
  if not refused then raise exception 'Other channel visible';end if;
  refused=false;begin perform public.arisa_whatsapp_monitor(gen_random_uuid(),thread);exception when insufficient_privilege then refused=true;end;
  if not refused then raise exception 'Other organization visible';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',gen_random_uuid(),'role','authenticated')::text,true);
  refused=false;begin perform public.arisa_whatsapp_inbox(org,thread,'pause');exception when insufficient_privilege then refused=true;end;
  if not refused then raise exception 'Nonmember can control thread';end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
  insert into public.arisa_whatsapp_messages(organization_id,thread_id,direction,content,occurred_at) values(org,thread,'inbound','Olá',now()) returning id into inbound;
  result=public.arisa_whatsapp_inbox(org,thread,'pause');
  if result->'selected'->>'human_requested'<>'true' then raise exception 'Pause not persisted';end if;
  if exists(select 1 from crm_private.arisa_whatsapp_reply_jobs where id=inbound and status in('pending','processing')) then raise exception 'Pause kept a queued reply';end if;
  insert into public.arisa_whatsapp_messages(organization_id,thread_id,direction,content,occurred_at) values(org,thread,'inbound','Paused message',now()) returning id into inbound;
  if exists(select 1 from crm_private.arisa_whatsapp_reply_jobs where id=inbound) then raise exception 'Paused inbound queued automatic reply';end if;
  if public.arisa_whatsapp_monitor(org,null,'Rollback panel','human')->>'total'<>'1' or public.arisa_whatsapp_monitor(org,null,'Rollback panel','automatic')->>'total'<>'0' then raise exception 'Mode filter mismatch';end if;
  perform public.arisa_whatsapp_inbox(org,thread,'resume');
  if exists(select 1 from crm_private.arisa_whatsapp_reply_jobs where thread_id=thread and status='pending') then raise exception 'Resume replayed old messages';end if;
  update public.arisa_whatsapp_threads set opted_out_at=now() where id=thread;
  refused=false;begin perform public.arisa_whatsapp_inbox(org,thread,'resume');exception when insufficient_privilege then refused=true;end;
  if not refused then raise exception 'Opt-out overridden';end if;
  update public.arisa_whatsapp_threads set opted_out_at=null where id=thread;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','service_role')::text,true);
  op=public.arisa_whatsapp_service('prepare',org,actor,jsonb_build_object('request_id',request_id,'operation_key',repeat('d',64),'payload_hash',repeat('e',64),'phone',phone,'content','Opening fixture','template_name','arisa'));
  result=public.arisa_whatsapp_service('request_status',org,actor,jsonb_build_object('request_id',request_id));
  if result->>'id' is distinct from op->>'id' or result->>'thread_id' is distinct from thread::text then raise exception 'Request cannot be recovered after reload';end if;
  refused=false;begin perform public.arisa_whatsapp_service('prepare',org,actor,jsonb_build_object('request_id',request_id,'operation_key',repeat('f',64),'payload_hash',repeat('e',64),'phone',phone||'1','content','Opening fixture','template_name','arisa'));exception when raise_exception then refused=true;end;
  if not refused then raise exception 'Changed request created a second send';end if;
  raise notice 'PASS: admin scoping, channel isolation, history paging, pause/resume, no old replay, opt-out and request recovery';
end $test$;
rollback;
