"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { getActivityRelatedLink } from "../erp/activities/activity-links";
import Link from 'next/link';
import { client, errorText } from '../arisa/chat-client';
import { displayDate, downloadText } from '../arisa/workspace-client';
import { SimulationView } from '../public-agent/ChatSimulation';
import type { PublicAgentSimulation } from '@/lib/public-agent/types';
import styles from '../arisa/workspace.module.css';
type Lead={id:string;person_name:string;phone:string|null;stage:string;record_status:string;next_action_at:string|null};
type Unit={id:string;unit_code:string;project_id:string;list_price:number};
export default function BiaCommercialPanel({organizationId,section}:{organizationId:string;section:'leads'|'simulations'}) {
  const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[leads,setLeads]=useState<Lead[]>([]),[total,setTotal]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [units,setUnits]=useState<Unit[]>([]),[simulation,setSimulation]=useState<PublicAgentSimulation|null>(null);
  useEffect(()=>{let live=true;const timer=setTimeout(()=>{setError('');setTotal(null);},0);void client().rpc('arisa_admin_query',{p_organization_id:organizationId,p_entity:section==='leads'?'crm_records':'crm_inventory_units',p_search:search||null,p_filters:section==='leads'?[]:[{column:'active',operator:'eq',value:true},{column:'status',operator:'eq',value:'disponivel'}],p_limit:20,p_offset:offset}).then(result=>{if(!live)return;if(result.error)setError(errorText(result.error));else{setTotal(result.data.total);if(section==='leads')setLeads(result.data.rows);else setUnits(result.data.rows);}});return()=>{live=false;clearTimeout(timer);};},[organizationId,section,search,offset]);
  async function simulate(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const unit=units.find(value=>value.id===form.get('unit'));if(!unit)return;setBusy(true);setError('');setSimulation(null);try{const result=await client().rpc('bia_manager_simulate',{p_organization_id:organizationId,p_unit_code:unit.unit_code,p_project_id:unit.project_id,p_requested_down_payment_pct:form.get('down')?Number(form.get('down'))/100:null,p_requested_months:form.get('months')?Number(form.get('months')):null,p_down_payment_installments:Number(form.get('downInstallments')||1),p_balloon_count:Number(form.get('balloons')||0),p_balloon_amount:Number(form.get('balloonAmount')||0)});if(result.error)throw result.error;setSimulation(result.data);}catch(error){setError(errorText(error));}finally{setBusy(false);}}
  return <section aria-label={section==='leads'?'Leads e funil comercial':'Simulações comerciais'}><p>{section==='leads'?'Leads atuais do CRM da sua organização. Você também pode pedir análises e ações à Bia no chat.':'Simule as condições atuais dos lotes disponíveis. As simulações pedidas no chat ficam salvas no histórico da conversa.'}</p><form className={styles.row} onSubmit={event=>{event.preventDefault();setSearch(query);setOffset(0);}}><label className={styles.grow}>{section==='leads'?'Buscar lead':'Buscar lote'}<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={section==='leads'?'Nome, telefone ou assunto':'Código do lote'}/></label><button type="submit">Buscar</button></form>{error&&<p role="alert" className={styles.error}>{error}</p>}<p role="status">{total===null?'Consultando CRM…':`${total} ${section==='leads'?'leads':'lotes'} encontrados`}</p>{section==='leads'?leads.map(lead=><article className={styles.card} key={lead.id}><h3>{lead.person_name}</h3><p>{lead.phone||'Telefone não informado'} · {lead.stage} · {lead.record_status}</p><small>Próxima ação: {lead.next_action_at?displayDate(lead.next_action_at):'Sem data registrada'}</small><div className={styles.row}><Link href={getActivityRelatedLink("crm_records",lead.id)?.href || "/?view=crm"}>Abrir no CRM</Link></div></article>):<form onSubmit={event=>void simulate(event)}><label>Lote<select name="unit" required><option value="">Selecione</option>{units.map(unit=><option key={unit.id} value={unit.id}>{unit.unit_code} · {Number(unit.list_price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</option>)}</select></label><div className={styles.row}><label>Entrada (%)<input name="down" type="number" min="0" max="90" step="0.1" placeholder="Mínima da política"/></label><label>Prazo em meses<input name="months" type="number" min="12" max="600" placeholder="Comparar prazos"/></label><label>Parcelas da entrada<input name="downInstallments" type="number" min="1" max="24" defaultValue="1"/></label><label>Quantidade de balões<input name="balloons" type="number" min="0" max="24" defaultValue="0"/></label><label>Valor de cada balão (R$)<input name="balloonAmount" type="number" min="0" step="0.01" defaultValue="0"/></label></div><button disabled={busy||!units.length}>{busy?'Calculando…':'Calcular simulação'}</button></form>}<div className={styles.row}><button disabled={!offset} onClick={()=>setOffset(value=>Math.max(0,value-20))}>Anteriores</button><span>Página {offset/20+1}</span><button disabled={total===null||offset+20>=total} onClick={()=>setOffset(value=>value+20)}>Próximos</button></div>{simulation&&<article className={styles.card}><SimulationView simulation={simulation}/><p>{simulation.disclaimer}</p><button onClick={()=>downloadText(`Simulação ${simulation.unitCode}.json`,JSON.stringify(simulation,null,2))}>Baixar simulação</button></article>}</section>;
}
