"use client";

import { FormEvent } from "react";
import { getSupabase } from "@/lib/supabase";
import type { CrmRecord, ErpData } from "../types";
import type { CrmEnterpriseData } from "./types";

export function ActivityModal({data,crm,lead,close,done}:{data:ErpData;crm:CrmEnterpriseData;lead:CrmRecord|null;close:()=>void;done:(message:string)=>Promise<void>}){
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const client=getSupabase();if(!client)return;const leadId=String(form.get("crm_record_id")||lead?.id||"");if(!leadId)throw new Error("Selecione um lead.");const completed=form.get("complete_now")==="on";const now=new Date().toISOString();const payload={organization_id:data.organization.id,crm_record_id:leadId,action_type:String(form.get("action_type")),channel:String(form.get("channel")),subject:String(form.get("subject")),scheduled_at:String(form.get("scheduled_at")||"")||null,completed_at:completed?now:null,action_status:completed?"concluida":"pendente",outcome:String(form.get("outcome")||"")||null,duration_minutes:Number(form.get("duration_minutes")||0)||null,assigned_to:String(form.get("assigned_to")||data.session.user.id),notes:String(form.get("notes")||"")||null,created_by:data.session.user.id};const result=await client.from("crm_actions").insert(payload);if(result.error)throw new Error(result.error.message);if(completed){const current=crm.records.find(item=>item.id===leadId);await client.from("crm_records").update({last_contact_at:now,first_response_at:current?.first_response_at||now,attempts:Number(current?.attempts||0)+1,stagnation_at:now,updated_at:now}).eq("id",leadId);}await done(completed?"Contato registrado.":"Atividade agendada.");close();}
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal crm5-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" type="button" onClick={close}>×</button><header><small>ATIVIDADE COMERCIAL</small><h2>{lead?`Interação com ${lead.person_name}`:"Nova atividade"}</h2></header><div className="form-grid"><label className="span-2">Lead<select name="crm_record_id" defaultValue={lead?.id||""} required><option value="">Selecione</option>{crm.records.map(item=><option key={item.id} value={item.id}>{item.person_name} · {item.company_name||item.phone||"Sem empresa"}</option>)}</select></label><label>Tipo<select name="action_type" defaultValue="contato"><option value="contato">Contato</option><option value="ligacao">Ligação</option><option value="whatsapp">WhatsApp</option><option value="email">E-mail</option><option value="reuniao">Reunião</option><option value="visita">Visita</option><option value="proposta">Proposta</option><option value="tarefa">Tarefa</option></select></label><label>Canal<select name="channel" defaultValue="whatsapp"><option>whatsapp</option><option>telefone</option><option>email</option><option>presencial</option><option>video</option><option>instagram</option></select></label><label className="span-2">Assunto<input name="subject" required placeholder="Ex.: Primeiro contato, visita ao empreendimento..."/></label><label>Agendamento<input name="scheduled_at" type="datetime-local" defaultValue={new Date(Date.now()+3600000).toISOString().slice(0,16)}/></label><label>Responsável<select name="assigned_to" defaultValue={data.session.user.id}>{data.members.filter(item=>item.active).map(item=><option key={item.user_id} value={item.user_id}>{data.profiles.find(p=>p.id===item.user_id)?.full_name||item.role}</option>)}</select></label><label>Resultado<select name="outcome" defaultValue=""><option value="">Aguardando</option><option value="atendeu">Atendeu</option><option value="nao_atendeu">Não atendeu</option><option value="retornar">Retornar</option><option value="interessado">Interessado</option><option value="sem_interesse">Sem interesse</option><option value="visita_agendada">Visita agendada</option><option value="proposta_solicitada">Proposta solicitada</option></select></label><label>Duração (minutos)<input name="duration_minutes" type="number" min="0"/></label><label className="checkbox span-2"><input name="complete_now" type="checkbox"/> Registrar como concluída agora</label><label className="span-2">Observações<textarea name="notes" rows={4}/></label></div><footer><button type="button" onClick={close}>Cancelar</button><button className="primary">Salvar atividade</button></footer></form></div>;
}
