"use client";
import {FormEvent} from "react";
import {getSupabase} from "@/lib/supabase";
import type {CrmRecord,ErpData} from "../types";
import type {CrmEnterpriseData} from "./types";
import {LeadCommercialFields} from "./lead-commercial-fields";
import {BuyerProfileFields} from "./buyer-profile-fields";
import {BuyerDocuments} from "./buyer-documents";
import {buildLeadPayload} from "./lead-form-payload";
import {LeadConversationHistory} from "./lead-conversation-history";
import styles from "./lead-modal-v52.module.css";

export function LeadModalV52({data,crm,lead,close,done}:{data:ErpData;crm:CrmEnterpriseData;lead:CrmRecord|null;close:()=>void;done:(message:string)=>Promise<void>}){const archived=lead?.record_status==="arquivada";async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(archived)return;const client=getSupabase();if(!client)return;const{score,payload}=buildLeadPayload(new FormData(e.currentTarget),data,crm,lead);const result=lead?await client.from("crm_records").update(payload).eq("id",lead.id):await client.from("crm_records").insert(payload);if(result.error)throw result.error;await done(lead?"Lead e cadastro do comprador atualizados.":`Lead criado com score ${score}. Designe o atendimento na Mesa SDR.`);close();}return <div className="modal-backdrop" onMouseDown={close}><form className="modal extra-large crm5-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" type="button" onClick={close}>×</button><header><small>{archived?"LEAD ARQUIVADO":lead?"EDITAR LEAD / COMPRADOR":"NOVO LEAD"}</small><h2>{lead?.person_name||"Cadastro comercial e contratual"}</h2><p>{archived?"Consulta somente leitura. O histórico comercial permanece preservado no ERP.":"Atendimento, qualificação, dados civis, endereço e documentação do comprador."}</p></header>{archived&&<div className={styles.archivedNotice} role="status"><strong>Cadastro arquivado e protegido contra alterações</strong><span>Para evitar reativação ou edição acidental, somente a consulta do cadastro, dos documentos e das conversas está disponível.</span></div>}<fieldset className={styles.editableFields} disabled={archived}><LeadCommercialFields data={data} crm={crm} lead={lead}/><BuyerProfileFields lead={lead}/><section className="buyer-form-section"><label>Observações<textarea name="notes" rows={4} defaultValue={lead?.notes||""}/></label></section></fieldset>{lead&&<BuyerDocuments data={data} leadId={lead.id} readOnly={archived}/>} {lead&&<LeadConversationHistory organizationId={data.organization.id} crmRecordId={lead.id} accessToken={data.session.access_token} leadName={lead.person_name}/>}<footer><button type="button" onClick={close}>{archived?"Fechar":"Cancelar"}</button>{!archived&&<button className="primary">{lead?"Salvar cadastro completo":"Criar lead"}</button>}</footer></form></div>}
