import type { CrmAction, CrmRecord } from "../types";

export type CrmSection = "overview" | "leads" | "sdr" | "pipelines" | "opportunities" | "salesmap" | "inventory" | "negotiation" | "proposals" | "contracts" | "agenda" | "campaigns" | "materials" | "automations" | "alerts" | "reports" | "teams" | "settings";
export interface CrmPipeline { id:string; organization_id:string; name:string; description:string|null; pipeline_type:string; is_default:boolean; active:boolean; }
export interface CrmStage { id:string; organization_id:string; pipeline_id:string; name:string; code:string; position:number; probability:number; color:string; sla_hours:number; is_won:boolean; is_lost:boolean; active:boolean; }
export interface CrmTeam { id:string; organization_id:string; name:string; team_type:string; manager_user_id:string|null; assignment_strategy:string; active:boolean; }
export interface CrmTeamMember { id:string; organization_id:string; team_id:string; user_id:string; team_role:string; weight:number; capacity:number; active:boolean; last_assigned_at:string|null; }
export interface CrmCampaign { id:string; organization_id:string; name:string; campaign_type:string; channel:string|null; status:string; project_id:string|null; negotiation_policy_id:string|null; owner_user_id:string|null; budget:number; spent:number; start_date:string|null; end_date:string|null; objective:string|null; audience:string|null; utm_source:string|null; utm_medium:string|null; utm_campaign:string|null; landing_page:string|null; notes:string|null; created_at:string; updated_at:string; }
export interface CrmFolder { id:string; organization_id:string; parent_id:string|null; name:string; description:string|null; project_id:string|null; visibility:string; }
export interface CrmAsset { id:string; organization_id:string; folder_id:string|null; project_id:string|null; name:string; asset_type:string; description:string|null; storage_path:string|null; external_url:string|null; mime_type:string|null; size_bytes:number|null; tags:string[]; audience:string|null; active:boolean; created_at:string; }
export interface CrmAutomation { id:string; organization_id:string; name:string; trigger_event:string; conditions:Record<string,unknown>; actions:Array<Record<string,unknown>>; active:boolean; priority:number; last_run_at:string|null; execution_count:number; }
export interface CrmAlert { id:string; organization_id:string; crm_record_id:string|null; alert_type:string; severity:string; title:string; message:string|null; assigned_to:string|null; due_at:string|null; status:string; created_at:string; }
export interface CrmTemplate { id:string; organization_id:string; name:string; channel:string; subject:string|null; body:string; variables:string[]; category:string|null; active:boolean; }
export interface CrmIntegration { id:string; organization_id:string; provider:string; display_name:string; status:string; configuration:Record<string,unknown>; last_sync_at:string|null; }
export interface CrmGoal { id:string; organization_id:string; goal_type:string; user_id:string|null; team_id:string|null; project_id:string|null; period_start:string; period_end:string; target_value:number; target_quantity:number; }
export interface CrmEnterpriseData { records:CrmRecord[]; actions:CrmAction[]; pipelines:CrmPipeline[]; stages:CrmStage[]; teams:CrmTeam[]; teamMembers:CrmTeamMember[]; campaigns:CrmCampaign[]; folders:CrmFolder[]; assets:CrmAsset[]; automations:CrmAutomation[]; alerts:CrmAlert[]; templates:CrmTemplate[]; integrations:CrmIntegration[]; goals:CrmGoal[]; }
