"use client";

import {useMemo,useState} from "react";

const sections=[
 {id:"inicio",icon:"◈",title:"Primeiros passos",summary:"Configuração inicial, usuários, empreendimentos e cadastros.",items:["Cadastre ou importe empreendimentos, centros, contas e contatos antes dos lançamentos.","Configure os perfis e permissões antes de convidar a equipe.","Use Administração da Plataforma para backup, migração e limpeza controlada.","No celular, use a navegação inferior e feche/reabra a PWA após atualizações."]},
 {id:"crm",icon:"◎",title:"CRM e leads",summary:"Captação, SDR, funis, propostas e contratos.",items:["Cadastre o lead e complete o Cadastro do Comprador antes do contrato.","Distribua o lead para SDR ou corretor e mantenha a próxima ação atualizada.","A proposta aprovada internamente pode ser enviada por link, e-mail ou WhatsApp.","O aceite do cliente gera o contrato; a assinatura gera os recebíveis automaticamente."]},
 {id:"marketing",icon:"◇",title:"Gestão de Marketing",summary:"Campanhas, produção, mídia e biblioteca de ativos.",items:["Crie a campanha e associe empreendimento, objetivo, público, orçamento e metas.","Use Produção para briefings, responsáveis, prazos e aprovações.","Em Ativos, use o botão Adicionar ativo para enviar arquivos ou cadastrar links.","Registre desempenho para acompanhar CPL, conversão, receita atribuída e ROAS."]},
 {id:"financeiro",icon:"▤",title:"Financeiro e DRE",summary:"Contas, caixa, aprovações, risco e resultado.",items:["Todo valor deve ser lançado com categoria, centro, empreendimento e contato quando aplicável.","Pagamentos com risco recebem data recomendada e dependem de decisão administrativa.","O administrador pode registrar a data negociada com o credor ou fornecedor.","Revise o mapeamento das categorias da DRE para refletir o plano gerencial da Évora."]},
 {id:"compras",icon:"▣",title:"Compras e serviços",summary:"Solicitação, aprovação, documentos e conta a pagar.",items:["Cadastre itens, fornecedor, necessidade, centro de custo e data prevista.","O sistema calcula o impacto no caixa e sugere a primeira data com cobertura.","Na decisão, o administrador pode escolher a data recomendada ou uma data negociada.","Depois da aprovação, gere a conta a pagar e anexe proposta, contrato, nota e comprovante."]},
 {id:"posvenda",icon:"♥",title:"Pós-venda e Portal",summary:"Jornada, cobrança, obra, documentos e relacionamento.",items:["Contratos assinados entram automaticamente na carteira de pós-venda.","Publique notícias, fotos, vídeos e marcos de obra no Portal do Cliente.","Use chamados, comunicados e cobrança para manter toda interação registrada.","Gere links individuais do portal e revogue-os quando necessário."]},
 {id:"governanca",icon:"⌘",title:"Usuários e governança",summary:"Perfis, permissões, auditoria, backup e restauração.",items:["O administrador pode criar usuários diretamente com senha temporária.","Permissões individuais podem permitir ou bloquear ações além do perfil padrão.","Crie backup integral verificado antes de limpar ou restaurar a base.","A auditoria registra decisões, alterações críticas, assinaturas e operações administrativas."]},
 {id:"assinatura",icon:"✓",title:"Propostas e assinaturas",summary:"Aceite, OTP, evidências e recebíveis.",items:["O cliente confirma nome, documento e leitura antes do aceite ou assinatura.","No modo de teste, o código aparece em uma simulação visível e fica marcado como teste.","Em produção, configure a API oficial do WhatsApp para envio do OTP.","Hash, IP, timestamp, dispositivo e geolocalização consentida integram o certificado."]}
];

export function HelpCenterV63(){const[query,setQuery]=useState(""),[open,setOpen]=useState<string|null>("inicio");const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?sections.filter(s=>`${s.title} ${s.summary} ${s.items.join(" ")}`.toLowerCase().includes(q)):sections},[query]);return <div className="help-center-v63"><section className="help-hero-v63"><div><small>CENTRAL DE CONHECIMENTO</small><h2>Ajuda para operar a plataforma com segurança.</h2><p>Orientações rápidas por processo, da captação do lead à assinatura, financeiro, marketing e pós-venda.</p></div><label>Buscar orientação<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex.: aprovar pagamento, cadastrar ativo, assinar contrato"/></label></section><section className="help-quick-v63"><a href="/marketing">Abrir Marketing</a><a href="/agenda">Abrir Agenda</a><a href="/crm">Abrir CRM</a><a href="/pos-venda">Abrir Pós-venda</a></section><section className="help-sections-v63">{filtered.map(section=><article key={section.id} className={open===section.id?"open":""}><button onClick={()=>setOpen(open===section.id?null:section.id)}><b>{section.icon}</b><span><strong>{section.title}</strong><small>{section.summary}</small></span><i>{open===section.id?"−":"+"}</i></button>{open===section.id&&<div><ol>{section.items.map((item,index)=><li key={item}><b>{String(index+1).padStart(2,"0")}</b><span>{item}</span></li>)}</ol></div>}</article>)}</section>{!filtered.length&&<div className="empty">Nenhuma orientação encontrada. Tente outra palavra.</div>}<section className="help-support-v63"><div><small>SUPORTE INTERNO</small><h3>Antes de alterar dados críticos</h3><p>Crie um backup integral, teste em homologação e registre a decisão na auditoria. Nunca compartilhe senhas ou códigos de assinatura.</p></div><a href="/">Voltar ao ERP</a></section></div>}
