// Best-effort restore order. The new canonical CRM parents precede their
// dependants; legacy circular sales references remain a separate hardening item.
export const organizationTables = [
  "organizations",
  "organization_members",
  "user_invitations",
  "system_settings",
  "role_access_profiles",
  "projects",
  "bank_accounts",
  "cost_centers",
  "revenue_centers",
  "financial_categories",
  "contacts",
  "financial_entries",
  "partner_payment_publications",
  "partner_landowner_repass_entries",
  "partner_landowner_publications",
  "partner_negotiations",
  "partner_negotiation_messages",
  "approval_requests",
  "document_attachments",
  "purchase_requests",
  "hr_employees",
  "hr_events",
  "hr_payroll_runs",
  "marketing_channels",
  "marketing_personas",
  "marketing_campaigns",
  "marketing_performance_snapshots",
  "marketing_assets",
  "marketing_calendar_items",
  "crm_pipelines",
  "crm_stages",
  "crm_teams",
  "crm_team_members",
  "crm_products",
  "crm_lead_sources",
  "crm_loss_reasons",
  "crm_meta_lead_routes",
  "crm_negotiation_parameters",
  "crm_campaigns",
  "crm_campaign_mappings",
  "crm_records",
  "crm_actions",
  "user_activities",
  "crm_lead_assignments",
  "crm_lead_assignment_events",
  "crm_contact_identities",
  "crm_opportunity_attributions",
  "crm_opportunity_events",
  "crm_asset_folders",
  "crm_marketing_assets",
  "crm_alerts",
  "crm_templates",
  "crm_integrations",
  "crm_goals",
  "crm_saved_segments",
  "crm_inventory_units",
  "crm_unit_reservations",
  "crm_proposals",
  "crm_proposal_approvals",
  "crm_proposal_installments",
  "crm_contract_templates",
  "crm_proposal_communications",
  "crm_contracts",
  "post_sale_journeys",
  "post_sale_tickets",
  "post_sale_collection_actions",
  "post_sale_renegotiations",
  "post_sale_communications",
  "post_sale_milestones",
  "post_sale_inspections",
  "post_sale_deeds",
  "post_sale_surveys",
  "post_sale_portal_tokens",
  "customer_portal_settings",
  "portal_content_items",
  "portal_messages",
  "marketing_requests",
  "communication_links",
  "data_import_jobs",
  "audit_logs",
] as const;

export const childTables = ["purchase_request_items", "hr_payroll_items"] as const;
export const bytes = (value: number) => value < 1024
  ? `${value} B`
  : value < 1048576
    ? `${(value / 1024).toFixed(1)} KB`
    : `${(value / 1048576).toFixed(1)} MB`;
export const dateTime = (value: string) => new Date(value).toLocaleString("pt-BR");
