"use client";
import {useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData} from "../types";
import {organizationTables,bytes,dateTime} from "./backup-config";
import {checksum,downloadBlob,gzipJson} from "./backup-utils";

type Run={id:string;status:string;file_name:string|null;storage_path:string|null;size_bytes:number|null;checksum:string|null;created_at:string;verified_at:string|null;table_counts:Record<string,number>;errors:string[]};
const PAGE_SIZE=500;

export function BackupCenter({data}:{data:ErpData}){
 const[runs,setRuns]=useState<Run[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[message,setMessage]=useState("");
 async function load(){const s=getSupabase();if(!s)return;const r=await s.from("backup_runs").select("*").eq("organization_id",data.organization.id).order("created_at",{ascending:false});if(!r.error)setRuns((r.data||[]) as Run[])}
 useEffect(()=>{void load()},[]);
 async function fetchAll(table:string,column:string,value:string){const s=getSupabase();if(!s)throw new Error("Supabase indisponível");const rows:unknown[]=[];for(let from=0;;from+=PAGE_SIZE){const r=await s.from(table).select("*").eq(column,value).range(from,from+PAGE_SIZE-1);if(r.error)throw new Error(`${table}: ${r.error.message}`);const page=r.data||[];rows.push(...page);if(page.length<PAGE_SIZE)break}return rows}
 async function fetchByIds(table:string,column:string,ids:string[]){const s=getSupabase();if(!s)throw new Error("Supabase indisponível");const rows:unknown[]=[];for(let offset=0;offset<ids.length;offset+=200){const chunk=ids.slice(offset,offset+200);for(let from=0;;from+=PAGE_SIZE){const r=await s.from(table).select("*").in(column,chunk).range(from,from+PAGE_SIZE-1);if(r.error)throw new Error(`${table}: ${r.error.message}`);const page=r.data||[];rows.push(...page);if(page.length<PAGE_SIZE)break}}return rows}
 async function createBackup(){setBusy(true);setMessage("");const s=getSupabase();if(!s){setBusy(false);setMessage("Supabase indisponível");return}const start=await s.from("backup_runs").insert({organization_id:data.organization.id,backup_type:"banco_e_metadados",status:"processando",includes_documents:false,created_by:data.session.user.id}).select("id").single();if(start.error){setMessage(start.error.message);setBusy(false);return}const counts:Record<string,number>={},tables:Record<string,unknown[]>={};try{
  for(let i=0;i<organizationTables.length;i++){const table=organizationTables[i];setProgress(`Exportando ${i+1}/${organizationTables.length}: ${table}`);const rows=await fetchAll(table,table==="organizations"?"id":"organization_id",data.organization.id);tables[table]=rows;counts[table]=rows.length}
  const memberIds=data.members.map(m=>m.user_id);if(memberIds.length){const rows=await fetchByIds("profiles","id",memberIds);tables.profiles=rows;counts.profiles=rows.length}
  const purchaseIds=((tables.purchase_requests||[]) as Array<{id:string}>).map(x=>x.id);if(purchaseIds.length){const rows=await fetchByIds("purchase_request_items","purchase_request_id",purchaseIds);tables.purchase_request_items=rows;counts.purchase_request_items=rows.length}
  const payrollIds=((tables.hr_payroll_runs||[]) as Array<{id:string}>).map(x=>x.id);if(payrollIds.length){const rows=await fetchByIds("hr_payroll_items","payroll_run_id",payrollIds);tables.hr_payroll_items=rows;counts.hr_payroll_items=rows.length}
  const payload={format:"evora-backup",version:"5.5",generated_at:new Date().toISOString(),organization:data.organization,created_by:data.session.user.id,tables,document_manifest:tables.document_attachments||[],errors:[]};setProgress("Compactando e verificando...");const blob=await gzipJson(payload),hash=await checksum(blob),fileName=`evora-backup-${new Date().toISOString().replace(/[:.]/g,"-")}.json.gz`,path=`${data.organization.id}/${start.data.id}/${fileName}`;const up=await s.storage.from("erp-backups").upload(path,blob,{contentType:"application/gzip",upsert:false});if(up.error)throw up.error;const saved=await s.from("backup_runs").update({status:"verificado",file_name:fileName,storage_path:path,size_bytes:blob.size,checksum:hash,table_counts:counts,errors:[],completed_at:new Date().toISOString(),verified_at:new Date().toISOString()}).eq("id",start.data.id);if(saved.error)throw saved.error;downloadBlob(blob,fileName);setMessage("Backup completo, verificado, armazenado e baixado com sucesso.");await load()
 }catch(e){const detail=e instanceof Error?e.message:"Erro não identificado";await s.from("backup_runs").update({status:"erro",errors:[detail],completed_at:new Date().toISOString()}).eq("id",start.data.id);setMessage(`Backup interrompido: ${detail}`);await load()}finally{setBusy(false);setProgress("")}}
 async function download(run:Run){if(!run.storage_path)return;const s=getSupabase();if(!s)return;const r=await s.storage.from("erp-backups").download(run.storage_path);if(r.error||!r.data){setMessage(r.error?.message||"Backup indisponível");return}downloadBlob(r.data,run.file_name||"evora-backup.json.gz")}
 return <div className="backup-center"><section className="admin-heading"><div><small>CONTINUIDADE E PROTEÇÃO</small><h2>Backup e recuperação</h2><p>Gere uma cópia paginada e verificável dos dados e do inventário de documentos antes de limpar a base.</p></div><button className="primary" onClick={createBackup} disabled={busy}>{busy?"Gerando...":"Criar backup agora"}</button></section>{progress&&<div className="feedback" role="status" aria-live="polite">{progress}</div>}{message&&<button className="notice" onClick={()=>setMessage("")} role="status">{message}</button>}<section className="admin-card"><header><div><small>HISTÓRICO</small><h3>Backups disponíveis</h3></div></header><div className="backup-list">{runs.map(r=><article key={r.id}><div><strong>{r.file_name||"Backup em processamento"}</strong><small>{dateTime(r.created_at)} · {r.size_bytes?bytes(r.size_bytes):"—"}</small></div><i data-status={r.status}>{r.status}</i><span>{r.checksum?`SHA-256 ${r.checksum.slice(0,16)}…`:"Aguardando verificação"}</span><button onClick={()=>download(r)} disabled={!r.storage_path}>Baixar</button></article>)}{!runs.length&&<p>Nenhum backup criado.</p>}</div></section><p className="hint">O pacote inclui todos os registros consultáveis e o inventário dos anexos. Os arquivos originais permanecem protegidos no Storage da Évora.</p></div>
}
