"use client";
import {useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData} from "../types";
import {organizationTables,bytes,dateTime} from "./backup-config";
import {checksum,downloadBlob,gzipJson} from "./backup-utils";

type Run={id:string;status:string;file_name:string|null;storage_path:string|null;size_bytes:number|null;checksum:string|null;created_at:string;verified_at:string|null;table_counts:Record<string,number>;errors:string[]};

export function BackupCenter({data}:{data:ErpData}){const[runs,setRuns]=useState<Run[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[message,setMessage]=useState("");
 async function load(){const s=getSupabase();if(!s)return;const r=await s.from("backup_runs").select("*").eq("organization_id",data.organization.id).order("created_at",{ascending:false});if(!r.error)setRuns((r.data||[]) as Run[])}
 useEffect(()=>{load()},[]);
 async function createBackup(){setBusy(true);setMessage("");const s=getSupabase();if(!s)return;const start=await s.from("backup_runs").insert({organization_id:data.organization.id,backup_type:"banco_e_metadados",status:"processando",includes_documents:false,created_by:data.session.user.id}).select("id").single();if(start.error){setMessage(start.error.message);setBusy(false);return}const counts:Record<string,number>={},errors:string[]=[],tables:Record<string,unknown[]>={};try{for(let i=0;i<organizationTables.length;i++){const table=organizationTables[i];setProgress(`Exportando ${i+1}/${organizationTables.length}: ${table}`);const q=table==="organizations"?s.from(table).select("*").eq("id",data.organization.id):s.from(table).select("*").eq("organization_id",data.organization.id);const r=await q;if(r.error){errors.push(`${table}: ${r.error.message}`);tables[table]=[]}else{tables[table]=r.data||[];counts[table]=(r.data||[]).length}}
 const memberIds=data.members.map(m=>m.user_id);if(memberIds.length){const r=await s.from("profiles").select("*").in("id",memberIds);tables.profiles=r.data||[];counts.profiles=(r.data||[]).length}
 const purchaseIds=(tables.purchase_requests as Array<{id:string}>||[]).map(x=>x.id);if(purchaseIds.length){const r=await s.from("purchase_request_items").select("*").in("purchase_request_id",purchaseIds);tables.purchase_request_items=r.data||[];counts.purchase_request_items=(r.data||[]).length}
 const payrollIds=(tables.hr_payroll_runs as Array<{id:string}>||[]).map(x=>x.id);if(payrollIds.length){const r=await s.from("hr_payroll_items").select("*").in("payroll_run_id",payrollIds);tables.hr_payroll_items=r.data||[];counts.hr_payroll_items=(r.data||[]).length}
 const payload={format:"evora-backup",version:"5.5",generated_at:new Date().toISOString(),organization:data.organization,created_by:data.session.user.id,tables,document_manifest:tables.document_attachments||[],errors};setProgress("Compactando e verificando...");const blob=await gzipJson(payload),hash=await checksum(blob),fileName=`evora-backup-${new Date().toISOString().replace(/[:.]/g,"-")}.json.gz`,path=`${data.organization.id}/${start.data.id}/${fileName}`;const up=await s.storage.from("erp-backups").upload(path,blob,{contentType:"application/gzip",upsert:false});if(up.error)throw up.error;await s.from("backup_runs").update({status:"verificado",file_name:fileName,storage_path:path,size_bytes:blob.size,checksum:hash,table_counts:counts,errors,completed_at:new Date().toISOString(),verified_at:new Date().toISOString()}).eq("id",start.data.id);downloadBlob(blob,fileName);setMessage("Backup verificado, armazenado e baixado com sucesso.");await load()}catch(e){await s.from("backup_runs").update({status:"erro",errors:[e instanceof Error?e.message:"erro"]}).eq("id",start.data.id);setMessage(e instanceof Error?e.message:"O backup falhou")}finally{setBusy(false);setProgress("")}}
 async function download(run:Run){if(!run.storage_path)return;const s=getSupabase();if(!s)return;const r=await s.storage.from("erp-backups").download(run.storage_path);if(r.error||!r.data){setMessage(r.error?.message||"Backup indisponível");return}downloadBlob(r.data,run.file_name||"evora-backup.json.gz")}
 return <div className="backup-center"><section className="admin-heading"><div><small>CONTINUIDADE E PROTEÇÃO</small><h2>Backup e recuperação</h2><p>Gere uma cópia compactada dos dados e do inventário de documentos antes de limpar a base.</p></div><button className="primary" onClick={createBackup} disabled={busy}>{busy?"Gerando...":"Criar backup agora"}</button></section>{progress&&<div className="feedback">{progress}</div>}{message&&<button className="notice" onClick={()=>setMessage("")}>{message}</button>}<section className="admin-card"><header><div><small>HISTÓRICO</small><h3>Backups disponíveis</h3></div></header><div className="backup-list">{runs.map(r=><article key={r.id}><div><strong>{r.file_name||"Backup em processamento"}</strong><small>{dateTime(r.created_at)} · {r.size_bytes?bytes(r.size_bytes):"—"}</small></div><i data-status={r.status}>{r.status}</i><span>{r.checksum?`SHA-256 ${r.checksum.slice(0,16)}…`:"Aguardando verificação"}</span><button onClick={()=>download(r)} disabled={!r.storage_path}>Baixar</button></article>)}{!runs.length&&<p>Nenhum backup criado.</p>}</div></section><p className="hint">O pacote inclui os dados e o inventário dos anexos. Os arquivos originais permanecem protegidos no Storage da Évora.</p></div>}
