"use client";
import {useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData} from "../types";

type Scope="operacional"|"completo";
const countTables=["financial_entries","partner_payment_publications","partner_landowner_publications","partner_landowner_repass_entries","partner_negotiations","partner_portal_links","crm_records","crm_lead_assignments","crm_lead_assignment_events","crm_opportunity_attributions","crm_opportunity_events","crm_campaign_mappings","crm_contact_identities","crm_products","crm_lead_sources","crm_loss_reasons","crm_meta_lead_routes","crm_proposals","crm_contracts","contacts","crm_inventory_units","document_attachments","audit_logs"];

export function DatabaseResetCenter({data,onDone}:{data:ErpData;onDone:()=>Promise<void>}){
 const[scope,setScope]=useState<Scope>("operacional"),[password,setPassword]=useState(""),[phrase,setPhrase]=useState(""),[preview,setPreview]=useState<Record<string,number>|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function loadPreview(){setBusy(true);setMessage("");const s=getSupabase();if(!s)return;const values:Record<string,number>={};for(const table of countTables){const r=await s.from(table).select("*",{count:"exact",head:true}).eq("organization_id",data.organization.id);values[table]=r.count||0}values.other_users=data.members.filter(m=>m.user_id!==data.session.user.id).length;setPreview(values);setBusy(false)}
 async function clear(){setMessage("");if(phrase!=="REINICIAR BASE EVORA"){setMessage("Digite exatamente REINICIAR BASE EVORA.");return}if(!password){setMessage("Informe sua senha atual.");return}if(!confirm(`Confirma a reinicialização ${scope} da base? Essa ação não pode ser desfeita.`))return;setBusy(true);try{const s=getSupabase();if(!s)throw new Error("Supabase indisponível");const email=data.session.user.email;if(!email)throw new Error("E-mail do administrador não localizado");const auth=await s.auth.signInWithPassword({email,password});if(auth.error)throw new Error("Senha inválida");const org=data.organization.id;const pause=await s.rpc("pause_meta_lead_ingress",{p_organization_id:org});if(pause.error)throw new Error(`crm_meta_pause: ${pause.error.message}`);const pauseData=pause.data&&typeof pause.data==="object"&&!Array.isArray(pause.data)?pause.data as Record<string,unknown>:{};const activeMetaRouteIds=Array.isArray(pauseData.active_route_ids)?pauseData.active_route_ids.filter((id):id is string=>typeof id==="string"):[];
  const del=async(table:string,column="organization_id")=>{const r=await s.from(table).delete().eq(column,org);if(r.error)throw new Error(`${table}: ${r.error.message}`)};
  const partnerReset=await s.rpc("reset_partner_portal_data",{p_organization_id:org});if(partnerReset.error&&!partnerReset.error.message.includes("does not exist"))throw new Error(`partner_portal: ${partnerReset.error.message}`);
  const proposalIds=(await s.from("crm_proposals").select("id").eq("organization_id",org)).data?.map(x=>x.id)||[];
  const purchaseIds=(await s.from("purchase_requests").select("id").eq("organization_id",org)).data?.map(x=>x.id)||[];
  const payrollIds=(await s.from("hr_payroll_runs").select("id").eq("organization_id",org)).data?.map(x=>x.id)||[];
  if(proposalIds.length)await s.from("crm_proposal_installments").delete().in("proposal_id",proposalIds);
  if(purchaseIds.length)await s.from("purchase_request_items").delete().in("purchase_request_id",purchaseIds);
  if(payrollIds.length)await s.from("hr_payroll_items").delete().in("payroll_run_id",payrollIds);
  for(const t of ["communication_links","data_import_jobs","post_sale_collection_actions","post_sale_renegotiations","post_sale_communications","post_sale_inspections","post_sale_deeds","post_sale_surveys","post_sale_tickets","post_sale_milestones","post_sale_portal_tokens","post_sale_journeys","crm_proposal_communications","crm_proposal_approvals","crm_contract_public_snapshots","crm_proposal_public_snapshots","crm_contracts","crm_proposals","crm_unit_reservations","crm_actions","crm_alerts","crm_automation_runs","crm_records","approval_requests","purchase_requests","hr_events","hr_payroll_runs","hr_employees","document_attachments","financial_entries","user_invitations","audit_logs"])await del(t);
  const canonicalReset=await s.rpc("purge_crm_canonical_data",{p_organization_id:org,p_include_catalogs:scope==="completo"});if(canonicalReset.error)throw new Error(`crm_canonical: ${canonicalReset.error.message}`);
  const otherIds=data.members.filter(m=>m.user_id!==data.session.user.id).map(m=>m.user_id);if(otherIds.length){await s.from("organization_members").delete().eq("organization_id",org).in("user_id",otherIds);await s.from("profiles").delete().in("id",otherIds)}
  if(scope==="completo"){const bridge=await s.from("crm_campaigns").update({marketing_campaign_id:null}).eq("organization_id",org);if(bridge.error)throw new Error(`crm_campaigns: ${bridge.error.message}`);for(const t of ["crm_inventory_units","contacts","projects","bank_accounts","cost_centers","revenue_centers","financial_categories"])await del(t)}else for(let i=0;i<activeMetaRouteIds.length;i+=250){const resume=await s.from("crm_meta_lead_routes").update({active:true}).eq("organization_id",org).in("id",activeMetaRouteIds.slice(i,i+250));if(resume.error)throw new Error(`crm_meta_resume: ${resume.error.message}`)}
  await s.from("audit_logs").insert({organization_id:org,user_id:data.session.user.id,action:"RESET_BASE",entity:"organization",new_data:{scope,executed_at:new Date().toISOString()}});setMessage("Base reinicializada com sucesso. O administrador e a organização foram preservados.");setPassword("");setPhrase("");setPreview(null);await onDone()
 }catch(err){setMessage(err instanceof Error?err.message:"A reinicialização falhou") }finally{setBusy(false)}}
 return <div className="database-reset-center"><section className="admin-heading"><div><small>ÁREA CRÍTICA</small><h2>Reinicializar a base</h2><p>Use somente antes do início oficial da operação ou após exportar um backup completo.</p></div></section><section className="admin-card danger-zone"><div className="reset-scope"><label><input type="radio" checked={scope==="operacional"} onChange={()=>setScope("operacional")}/><span><strong>Limpeza operacional</strong><small>Remove lançamentos, leads, propostas, contratos, documentos, RH, compras e pós-venda; preserva cadastros estruturais.</small></span></label><label><input type="radio" checked={scope==="completo"} onChange={()=>setScope("completo")}/><span><strong>Limpeza completa</strong><small>Também remove clientes, fornecedores, lotes, empreendimentos, contas e centros gerenciais.</small></span></label></div><button onClick={loadPreview} disabled={busy}>Gerar prévia da limpeza</button>{preview&&<div className="reset-preview">{Object.entries(preview).map(([k,v])=><article key={k}><small>{k.replaceAll("_"," ")}</small><strong>{v}</strong></article>)}</div>}<div className="form-grid two"><label>Senha atual do administrador<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><label>Confirmação<input value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder="REINICIAR BASE EVORA"/></label></div><button className="danger-button wide" disabled={busy||!preview} onClick={clear}>{busy?"Processando...":"Reinicializar base selecionada"}</button>{message&&<div className="feedback">{message}</div>}</section></div>}
