"use client";
import {FormEvent,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {AdminProps} from "../views-admin";
import {roleLabels} from "../utils";
import {PanelTitle} from "../views-dashboard";
export function InviteModal({data,close,mutate}:AdminProps&{close:()=>void}){const[mode,setMode]=useState<"invite"|"direct">("invite"),[result,setResult]=useState("");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setResult("");const form=new FormData(event.currentTarget),supabase=getSupabase();if(!supabase)return;const payload={organization_id:data.organization.id,email:String(form.get("email")||"").toLowerCase(),full_name:String(form.get("full_name")||""),role:String(form.get("role")||"consulta"),mode,temporary_password:String(form.get("temporary_password")||"")};const{data:response,error}=await supabase.functions.invoke("admin-user-management",{body:payload});if(error||response?.error){setResult(response?.error||error?.message||"Não foi possível concluir.");return}if(mode==="direct"){setResult(`Usuário criado. Senha temporária: ${response.temporary_password}`);await mutate(async()=>Promise.resolve(),"Usuário criado diretamente.");return}await mutate(async()=>{const{error:dbError}=await supabase.from("user_invitations").upsert({organization_id:data.organization.id,email:payload.email,full_name:payload.full_name,role:payload.role,invited_by:data.session.user.id,accepted_at:null,expires_at:new Date(Date.now()+14*86400000).toISOString()},{onConflict:"organization_id,email"});if(dbError)throw dbError},"Convite enviado por e-mail.");close()}
 return <div className="modal-backdrop" onMouseDown={close}><form className="modal invite-v58" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><PanelTitle eyebrow="NOVO ACESSO" title="Adicionar usuário"/><button className="modal-close" type="button" onClick={close}>×</button><nav className="invite-mode"><button type="button" className={mode==="invite"?"active":""} onClick={()=>setMode("invite")}>Enviar convite</button><button type="button" className={mode==="direct"?"active":""} onClick={()=>setMode("direct")}>Criar diretamente</button></nav><div className="form-grid"><label className="span-2">Nome completo<input name="full_name" required/></label><label className="span-2">E-mail<input name="email" type="email" required/></label><label className="span-2">Perfil<select name="role" defaultValue="consulta">{Object.entries(roleLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{mode==="direct"&&<label className="span-2">Senha temporária<input name="temporary_password" type="text" placeholder="Deixe em branco para gerar automaticamente"/></label>}</div><div className="info-box">{mode==="invite"?"O Supabase enviará um convite real para o e-mail informado.":"O usuário será criado com e-mail confirmado e deverá trocar a senha temporária no primeiro acesso."}</div>{result&&<div className="feedback">{result}</div>}<footer><button type="button" onClick={close}>Cancelar</button><button className="primary">{mode==="invite"?"Enviar convite":"Criar usuário"}</button></footer></form></div>}
