"use client";
import {useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData} from "../types";
import {organizationTables,bytes,dateTime} from "./backup-config";

type Run={id:string;file_name:string|null;storage_path:string|null;status:string;created_at:string;size_bytes:number|null};
type Package={format:string;version:string;organization:{id:string};tables:Record<string,Array<Record<string,unknown>>>};
const protectedTables=new Set(["organizations","organization_members","profiles","backup_runs","restore_jobs","audit_logs"]);
function octal(bytes:Uint8Array,start:number,length:number){return parseInt(new TextDecoder().decode(bytes.slice(start,start+length)).replace(/\0.*$/,"").trim()||"0",8)}
async function extractDatabase(blob:Blob){let source=new Uint8Array(await blob.arrayBuffer());if(source[0]===31&&source[1]===139){const stream=new Blob([source]).stream().pipeThrough(new DecompressionStream("gzip"));source=new Uint8Array(await new Response(stream).arrayBuffer())}let offset=0;while(offset+512<=source.length){const header=source.slice(offset,offset+512);if(header.every(v=>v===0))break;const dec=new TextDecoder(),name=dec.decode(header.slice(0,100)).replace(/\0.*$/,"");const prefix=dec.decode(header.slice(345,500)).replace(/\0.*$/,"");const path=prefix?`${prefix}/${name}`:name,size=octal(header,124,12);offset+=512;const body=source.slice(offset,offset+size);if(path==="database.json")return JSON.parse(dec.decode(body)) as Package;offset+=Math.ceil(size/512)*512}throw new Error("O arquivo database.json não foi encontrado no pacote.")}
export function RestoreCenter({data,reload}:{data:ErpData;reload:()=>Promise<void>}){const[runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState(""),[file,setFile]=useState<File|null>(null),[pkg,setPkg]=useState<Package|null>(null),[message,setMessage]=useState(""),[progress,setProgress]=useState(""),[confirmText,setConfirmText]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const s=getSupabase();if(!s)return;const r=await s.from("backup_runs").select("id,file_name,storage_path,status,created_at,size_bytes").eq("organization_id",data.organization.id).in("status",["verificado","parcial"]).order("created_at",{ascending:false});if(!r.error)setRuns(r.data||[])}useEffect(()=>{load()},[]);
 async function sourceBlob(){if(file)return file;const run=runs.find(r=>r.id===selected);if(!run?.storage_path)throw new Error("Selecione um backup ou envie um arquivo.");const s=getSupabase();if(!s)throw new Error("Supabase indisponível.");const r=await s.storage.from("erp-backups").download(run.storage_path);if(r.error||!r.data)throw new Error(r.error?.message||"Backup indisponível.");return r.data}
 async function validate(){setBusy(true);setMessage("");try{const parsed=await extractDatabase(await sourceBlob());if(parsed.format!=="evora-backup"||!parsed.tables)throw new Error("Formato de backup inválido.");if(parsed.organization?.id!==data.organization.id)throw new Error("O backup pertence a outra organização.");setPkg(parsed);setMessage(`Pacote validado: versão ${parsed.version}, ${Object.keys(parsed.tables).length} conjuntos de dados.`)}catch(e){setPkg(null);setMessage(e instanceof Error?e.message:"Falha na validação.")}finally{setBusy(false)}}
 async function restore(){if(data.membership.role!=="admin")return setMessage("Apenas o administrador pode restaurar a base.");if(!pkg)return setMessage("Valide o pacote antes da restauração.");if(confirmText!=="RECUPERAR BASE EVORA")return setMessage("Digite a frase de confirmação exatamente como apresentada.");const verified=runs.find(r=>r.status==="verificado"&&Date.now()-new Date(r.created_at).getTime()<86400000);if(!verified)return setMessage("Crie um backup verificado nas últimas 24 horas antes de restaurar.");if(!confirm("A restauração substituirá os dados operacionais atuais. Continuar?"))return;setBusy(true);const s=getSupabase();if(!s)return;const job=await s.from("restore_jobs").insert({organization_id:data.organization.id,backup_run_id:selected||null,file_name:file?.name||runs.find(r=>r.id===selected)?.file_name,status:"processando",mode:"producao",validation:{version:pkg.version,tables:Object.keys(pkg.tables).length},requested_by:data.session.user.id,approved_by:data.session.user.id}).select("id").single();try{const ordered=organizationTables.filter(t=>!protectedTables.has(t));for(const table of [...ordered].reverse()){setProgress(`Limpando ${table}...`);const del=await s.from(table).delete().eq("organization_id",data.organization.id);if(del.error&&!del.error.message.includes("does not exist"))throw new Error(`${table}: ${del.error.message}`)}for(const table of ordered){const rows=(pkg.tables[table]||[]).map(row=>({...row,organization_id:data.organization.id}));if(!rows.length)continue;setProgress(`Restaurando ${table}: ${rows.length} registro(s)...`);for(let i=0;i<rows.length;i+=250){const up=await s.from(table).upsert(rows.slice(i,i+250),{onConflict:"id"});if(up.error)throw new Error(`${table}: ${up.error.message}`)}}if(job.data?.id)await s.from("restore_jobs").update({status:"concluido",completed_at:new Date().toISOString()}).eq("id",job.data.id);setMessage("Restauração concluída. Recarregando a plataforma...");await reload();setTimeout(()=>location.href="/",1200)}catch(e){if(job.data?.id)await s.from("restore_jobs").update({status:"erro",errors:[e instanceof Error?e.message:"erro"],completed_at:new Date().toISOString()}).eq("id",job.data.id);setMessage(e instanceof Error?e.message:"A restauração falhou.")}finally{setBusy(false);setProgress("")}}
 return <div className="restore-center"><section className="admin-heading"><div><small>RECUPERAÇÃO CONTROLADA</small><h2>Recuperar backup</h2><p>Valide e restaure dados operacionais usando o histórico ou um pacote baixado.</p></div></section>{message&&<button className="notice" onClick={()=>setMessage("")}>{message}</button>}{progress&&<div className="feedback">{progress}</div>}<section className="admin-card restore-source"><header><div><small>ORIGEM</small><h3>Selecionar pacote</h3></div></header><label>Backup armazenado<select value={selected} onChange={e=>{setSelected(e.target.value);setFile(null);setPkg(null)}}><option value="">Selecione</option>{runs.map(r=><option key={r.id} value={r.id}>{r.file_name} · {r.status} · {dateTime(r.created_at)} · {r.size_bytes?bytes(r.size_bytes):"—"}</option>)}</select></label><span>ou</span><label>Upload de arquivo<input type="file" accept=".tar,.gz,.tgz,.json.gz" onChange={e=>{setFile(e.target.files?.[0]||null);setSelected("");setPkg(null)}}/></label><button onClick={validate} disabled={busy||(!selected&&!file)}>Validar pacote</button></section><section className="admin-card restore-confirm"><header><div><small>EXECUÇÃO</small><h3>Restaurar dados operacionais</h3></div></header><div className="critical-warning"><strong>Proteções preservadas</strong><p>Organização, administrador, usuários, auditoria e histórico de backups não serão substituídos.</p></div><label>Confirmação<input value={confirmText} onChange={e=>setConfirmText(e.target.value)} placeholder="RECUPERAR BASE EVORA"/></label><button className="danger" onClick={restore} disabled={busy||!pkg||confirmText!=="RECUPERAR BASE EVORA"}>Recuperar backup validado</button></section></div>}
