"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData,Role} from "../types";
import {allPermissionKeys,permissionGroups,roleNames,roles} from "./permissions-config";

type Row={id?:string;role:Role;permission_key:string;allowed:boolean};
export function RolePermissionsView({data,reload}:{data:ErpData;reload:()=>Promise<void>}){const[selectedRole,setSelectedRole]=useState<Role>("diretoria"),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[memberId,setMemberId]=useState(""),[overrides,setOverrides]=useState<Record<string,boolean|undefined>>({});
 async function load(){const s=getSupabase();if(!s)return;const r=await s.from("role_permissions").select("*").eq("organization_id",data.organization.id);if(!r.error)setRows((r.data||[]) as Row[])}
 useEffect(()=>{load()},[]);useEffect(()=>{const m=data.members.find(x=>x.user_id===memberId);setOverrides(m?.permissions||{})},[memberId,data.members]);
 const roleMap=useMemo(()=>Object.fromEntries(rows.filter(r=>r.role===selectedRole).map(r=>[r.permission_key,r.allowed])),[rows,selectedRole]);
 function toggle(key:string,value:boolean){setRows(current=>{const found=current.find(r=>r.role===selectedRole&&r.permission_key===key);return found?current.map(r=>r===found?{...r,allowed:value}:r):[...current,{role:selectedRole,permission_key:key,allowed:value}]})}
 async function saveRole(){setBusy(true);setMessage("");const s=getSupabase();if(!s)return;const payload=allPermissionKeys.map(key=>({organization_id:data.organization.id,role:selectedRole,permission_key:key,allowed:selectedRole==="admin"?true:!!rows.find(r=>r.role===selectedRole&&r.permission_key===key)?.allowed,updated_by:data.session.user.id,updated_at:new Date().toISOString()}));const r=await s.from("role_permissions").upsert(payload,{onConflict:"organization_id,role,permission_key"});setBusy(false);setMessage(r.error?r.error.message:"Perfil salvo com sucesso.");if(!r.error){await load();await reload()}}
 async function saveUser(){if(!memberId)return;setBusy(true);setMessage("");const s=getSupabase();if(!s)return;const clean=Object.fromEntries(Object.entries(overrides).filter(([,v])=>typeof v==="boolean"));const r=await s.from("organization_members").update({permissions:clean,updated_at:new Date().toISOString()}).eq("organization_id",data.organization.id).eq("user_id",memberId);setBusy(false);setMessage(r.error?r.error.message:"Exceções individuais salvas.");if(!r.error)await reload()}
 return <div className="permission-admin"><section className="admin-heading"><div><small>PERFIS E ALÇADAS</small><h1>Níveis de acesso</h1><p>Defina o que cada perfil pode visualizar e operar. O administrador mantém acesso integral.</p></div></section>{message&&<button className="notice" onClick={()=>setMessage("")}>{message}</button>}<section className="permission-layout"><aside className="role-selector">{roles.map(role=><button key={role} className={selectedRole===role?"active":""} onClick={()=>setSelectedRole(role)}><strong>{roleNames[role]}</strong><small>{data.members.filter(m=>m.role===role).length} usuário(s)</small></button>)}</aside><article className="admin-card"><header><div><small>PERFIL SELECIONADO</small><h2>{roleNames[selectedRole]}</h2></div><button className="primary" onClick={saveRole} disabled={busy||selectedRole==="admin"}>{selectedRole==="admin"?"Acesso integral":"Salvar perfil"}</button></header><div className="permission-groups">{permissionGroups.map(group=><section key={group.name}><h3>{group.name}</h3>{group.items.map(item=><label key={item.key}><span><strong>{item.label}</strong><small>{item.key}</small></span><input type="checkbox" checked={selectedRole==="admin"||!!roleMap[item.key]} disabled={selectedRole==="admin"} onChange={e=>toggle(item.key,e.target.checked)}/></label>)}</section>)}</div></article></section><section className="admin-card individual-permissions"><header><div><small>EXCEÇÕES INDIVIDUAIS</small><h2>Personalização por usuário</h2><p>Uma exceção individual substitui o perfil apenas para o usuário selecionado.</p></div></header><label>Usuário<select value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Selecione</option>{data.members.map(m=>{const p=data.profiles.find(x=>x.id===m.user_id);return <option key={m.user_id} value={m.user_id}>{p?.full_name||p?.email||m.user_id} · {roleNames[m.role]}</option>})}</select></label>{memberId&&<div className="override-grid">{permissionGroups.flatMap(g=>g.items).map(item=><label key={item.key}><span>{item.label}</span><select value={overrides[item.key]===true?"allow":overrides[item.key]===false?"deny":"inherit"} onChange={e=>setOverrides(v=>({...v,[item.key]:e.target.value==="inherit"?undefined:e.target.value==="allow"}))}><option value="inherit">Herdar do perfil</option><option value="allow">Permitir</option><option value="deny">Bloquear</option></select></label>)}</div>}<button className="primary" disabled={!memberId||busy} onClick={saveUser}>Salvar exceções</button></section></div>}
