"use client";
import {useMemo,useState} from "react";
import type {ErpData} from "../types";
import type {PostSaleData} from "./types";
import {contractContext} from "./utils";
import {PortalLinks} from "./portal-links";
import {PortalSettingsForm,portalDefaults,type PortalSettings} from "./portal-settings-form";
import {PortalContentManager} from "./portal-content-manager";
export function CustomerPortalAdmin({data,ps}:{data:ErpData;ps:PostSaleData}){const[settings,setSettings]=useState<PortalSettings>(portalDefaults),[contractId,setContractId]=useState(ps.contracts.find(c=>c.status==="assinado")?.id||""),[tab,setTab]=useState<"design"|"content"|"links">("design");const signed=ps.contracts.filter(c=>c.status==="assinado"),context=useMemo(()=>contractId?contractContext(data,ps,contractId):null,[contractId,ps,data]);return <div className="portal-admin portal-admin-v58"><section className="post-sale-heading"><div><small>EXPERIÊNCIA DIGITAL DO CLIENTE</small><h2>Portal do cliente</h2><p>Uma landing page protegida para relacionamento, conteúdo, obra, documentos, financeiro e atendimento.</p></div><a className="button-link" href={contractId?`/cliente/preview-${contractId}`:"#"}>Abrir referência visual</a></section><nav className="portal-admin-tabs"><button className={tab==="design"?"active":""} onClick={()=>setTab("design")}>Design e experiência</button><button className={tab==="content"?"active":""} onClick={()=>setTab("content")}>Conteúdo e obra</button><button className={tab==="links"?"active":""} onClick={()=>setTab("links")}>Links e acessos</button></nav>{tab==="design"&&<section className="portal-admin-grid"><PortalSettingsForm data={data} onSaved={setSettings}/><article className="portal-preview-card portal-preview-rich"><header><small>PRÉVIA DA LANDING PAGE</small><h3>{settings.portal_title}</h3></header><select value={contractId} onChange={e=>setContractId(e.target.value)}><option value="">Selecione um contrato</option>{signed.map(c=>{const x=contractContext(data,ps,c.id);return <option key={c.id} value={c.id}>{x.proposal?.customer_name} · {c.contract_number}</option>})}</select>{context&&<div className="portal-mini" style={{"--portal-primary":settings.theme_primary,"--portal-accent":settings.theme_accent} as React.CSSProperties}><div className="portal-mini-hero"><small>{context.project?.name}</small><h2>{context.unit?.unit_code}</h2><p>{settings.hero_message}</p><button>Explorar minha jornada</button></div><div className="portal-mini-grid"><span>Obras e novidades</span><span>Financeiro</span><span>Documentos</span><span>Atendimento</span></div></div>}</article></section>}{tab==="content"&&<PortalContentManager data={data}/>} {tab==="links"&&<PortalLinks data={data} ps={ps}/>}</div>}
