"use client";
import {FormEvent,useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData} from "../types";

type Item={id:string;content_type:string;title:string;subtitle:string|null;body:string|null;media_url:string|null;cta_label:string|null;cta_url:string|null;featured:boolean;active:boolean;project_id:string|null;created_at:string};
export function PortalContentManager({data}:{data:ErpData}){const[items,setItems]=useState<Item[]>([]),[show,setShow]=useState(false),[message,setMessage]=useState("");async function load(){const s=getSupabase();if(!s)return;const r=await s.from("portal_content_items").select("*").eq("organization_id",data.organization.id).order("featured",{ascending:false}).order("created_at",{ascending:false});if(r.error)setMessage(r.error.message);else setItems(r.data||[])}useEffect(()=>{load()},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),s=getSupabase();if(!s)return;const r=await s.from("portal_content_items").insert({organization_id:data.organization.id,project_id:f.get("project_id")||null,content_type:f.get("content_type"),title:f.get("title"),subtitle:f.get("subtitle")||null,body:f.get("body")||null,media_url:f.get("media_url")||null,cta_label:f.get("cta_label")||null,cta_url:f.get("cta_url")||null,featured:f.get("featured")==="on",active:true,created_by:data.session.user.id});if(r.error)setMessage(r.error.message);else{setShow(false);await load()}}
 async function toggle(item:Item){const s=getSupabase();if(!s)return;await s.from("portal_content_items").update({active:!item.active,updated_at:new Date().toISOString()}).eq("id",item.id);await load()}
 return <section className="portal-editor-card"><header><div><small>CONTEÚDO COMERCIAL</small><h2>Publicações do portal</h2><p>Avanços de obra, notícias, vídeos, orientações e chamadas comerciais.</p></div><button className="primary" onClick={()=>setShow(true)}>+ Nova publicação</button></header><div className="portal-editor-list">{items.map(item=><article key={item.id} className={!item.active?"inactive":""}><div className="portal-content-icon">{item.content_type==="video"?"▶":item.content_type==="imagem"?"▧":"T"}</div><div><small>{item.content_type} · {item.featured?"destaque":"publicação"}</small><strong>{item.title}</strong><p>{item.subtitle||item.body||"Sem descrição"}</p></div><span>{item.project_id?data.projects.find(p=>p.id===item.project_id)?.name:"Todos os empreendimentos"}</span><button onClick={()=>toggle(item)}>{item.active?"Desativar":"Ativar"}</button></article>)}{!items.length&&<p>Nenhuma publicação criada.</p>}</div>{show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><form className="modal large" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={()=>setShow(false)}>×</button><header><small>NOVA PUBLICAÇÃO</small><h2>Conteúdo do portal</h2></header><div className="form-grid three"><label className="span-2">Título<input name="title" required/></label><label>Tipo<select name="content_type"><option value="texto">Texto / notícia</option><option value="video">Vídeo</option><option value="imagem">Imagem</option><option value="obra">Avanço de obra</option><option value="comunicado">Comunicado</option><option value="oferta">Oportunidade</option></select></label><label className="span-2">Subtítulo<input name="subtitle"/></label><label>Empreendimento<select name="project_id"><option value="">Todos</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="span-3">Texto<textarea name="body" rows={6}/></label><label className="span-3">URL de imagem ou vídeo<input name="media_url" type="url" placeholder="YouTube, Vimeo, imagem ou tour virtual"/></label><label>Texto do botão<input name="cta_label" placeholder="Saiba mais"/></label><label className="span-2">Link do botão<input name="cta_url" type="url"/></label><label><input name="featured" type="checkbox"/> Publicação em destaque</label></div><footer><button type="button" onClick={()=>setShow(false)}>Cancelar</button><button className="primary">Publicar conteúdo</button></footer></form></div>}</section>}
