"use client";
import {FormEvent,useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData} from "../types";
export type PortalSettings={id?:string;portal_title:string;welcome_message:string;hero_message:string;support_email:string;support_phone:string;show_financial:boolean;show_works:boolean;show_documents:boolean;show_tickets:boolean;show_journey:boolean;show_deed:boolean;allow_ticket_creation:boolean;theme_primary:string;theme_accent:string};
export const portalDefaults:PortalSettings={portal_title:"Portal do Cliente",welcome_message:"Acompanhe seu contrato, pagamentos, obra e relacionamento com a Évora.",hero_message:"Sua jornada com a Évora, em um só lugar.",support_email:"",support_phone:"",show_financial:true,show_works:true,show_documents:true,show_tickets:true,show_journey:true,show_deed:true,allow_ticket_creation:false,theme_primary:"#1D5271",theme_accent:"#79B82B"};
export function PortalSettingsForm({data,onSaved}:{data:ErpData;onSaved:(s:PortalSettings)=>void}){const[settings,setSettings]=useState<PortalSettings>(portalDefaults),[message,setMessage]=useState("");useEffect(()=>{(async()=>{const s=getSupabase();if(!s)return;const r=await s.from("customer_portal_settings").select("*").eq("organization_id",data.organization.id).is("project_id",null).maybeSingle();if(r.data){const next={...portalDefaults,...r.data};setSettings(next);onSaved(next)}})()},[]);
 async function save(e:FormEvent){e.preventDefault();const s=getSupabase();if(!s)return;const existing=await s.from("customer_portal_settings").select("id").eq("organization_id",data.organization.id).is("project_id",null).maybeSingle();const payload={...settings,organization_id:data.organization.id,project_id:null,updated_by:data.session.user.id,updated_at:new Date().toISOString()};delete (payload as any).id;const r=existing.data?await s.from("customer_portal_settings").update(payload).eq("id",existing.data.id):await s.from("customer_portal_settings").insert(payload);setMessage(r.error?r.error.message:"Configurações salvas.");if(!r.error)onSaved(settings)}
 const toggle=(key:keyof PortalSettings,value:boolean)=>setSettings(v=>({...v,[key]:value}));
 return <form className="post-sale-panel" onSubmit={save}><header><div><small>APRESENTAÇÃO</small><h3>Conteúdo e identidade</h3></div></header><div className="form-grid two"><label>Título<input value={settings.portal_title} onChange={e=>setSettings(v=>({...v,portal_title:e.target.value}))}/></label><label>Mensagem principal<input value={settings.hero_message} onChange={e=>setSettings(v=>({...v,hero_message:e.target.value}))}/></label><label className="span-2">Boas-vindas<textarea rows={3} value={settings.welcome_message} onChange={e=>setSettings(v=>({...v,welcome_message:e.target.value}))}/></label><label>E-mail de suporte<input type="email" value={settings.support_email} onChange={e=>setSettings(v=>({...v,support_email:e.target.value}))}/></label><label>WhatsApp / telefone<input value={settings.support_phone} onChange={e=>setSettings(v=>({...v,support_phone:e.target.value}))}/></label><label>Cor principal<input type="color" value={settings.theme_primary} onChange={e=>setSettings(v=>({...v,theme_primary:e.target.value}))}/></label><label>Cor de destaque<input type="color" value={settings.theme_accent} onChange={e=>setSettings(v=>({...v,theme_accent:e.target.value}))}/></label></div><div className="portal-switches">{([["show_journey","Jornada"],["show_financial","Financeiro"],["show_works","Obras"],["show_documents","Documentos"],["show_tickets","Atendimentos"],["show_deed","Escritura"]] as Array<[keyof PortalSettings,string]>).map(([key,label])=><label key={key}><input type="checkbox" checked={!!settings[key]} onChange={e=>toggle(key,e.target.checked)}/><span>{label}</span></label>)}</div><button className="primary">Salvar configurações</button>{message&&<div className="feedback">{message}</div>}</form>}
