"use client";
import {useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData} from "../types";
import type {PostSaleData} from "./types";
import {contractContext} from "./utils";
type Token={id:string;contract_id:string;token:string;active:boolean;expires_at:string;last_access_at:string|null;created_at:string};
export function PortalLinks({data,ps}:{data:ErpData;ps:PostSaleData}){const[tokens,setTokens]=useState<Token[]>([]),[logs,setLogs]=useState<any[]>([]),[message,setMessage]=useState("");async function load(){const s=getSupabase();if(!s)return;const[t,l]=await Promise.all([s.from("post_sale_portal_tokens").select("*").eq("organization_id",data.organization.id).order("created_at",{ascending:false}),s.from("post_sale_portal_access_logs").select("*").eq("organization_id",data.organization.id).order("accessed_at",{ascending:false}).limit(200)]);setTokens((t.data||[]) as Token[]);setLogs(l.data||[])}useEffect(()=>{load()},[]);
 async function createLink(contractId:string){const s=getSupabase();if(!s)return;await s.from("post_sale_portal_tokens").update({active:false}).eq("contract_id",contractId).eq("active",true);const r=await s.from("post_sale_portal_tokens").insert({organization_id:data.organization.id,contract_id:contractId,created_by:data.session.user.id,expires_at:new Date(Date.now()+30*86400000).toISOString()}).select("token").single();if(r.error){setMessage(r.error.message);return}await navigator.clipboard.writeText(`${location.origin}/cliente/${r.data.token}`);setMessage("Novo link copiado. Validade: 30 dias.");await load()}
 async function revoke(id:string){const s=getSupabase();if(!s)return;const r=await s.from("post_sale_portal_tokens").update({active:false}).eq("id",id);setMessage(r.error?r.error.message:"Acesso revogado.");if(!r.error)await load()}
 const signed=ps.contracts.filter(c=>c.status==="assinado");return <section className="post-sale-panel"><header><div><small>ACESSOS INDIVIDUAIS</small><h3>Links por contrato</h3></div></header>{message&&<button className="notice" onClick={()=>setMessage("")}>{message}</button>}<div className="portal-token-list">{signed.map(c=>{const x=contractContext(data,ps,c.id),token=tokens.find(t=>t.contract_id===c.id&&t.active&&new Date(t.expires_at)>new Date()),accesses=logs.filter(l=>l.contract_id===c.id).length;return <article key={c.id}><div><strong>{x.proposal?.customer_name}</strong><small>{c.contract_number} · {x.project?.name} · {x.unit?.unit_code}</small></div><span>{token?`Ativo até ${new Date(token.expires_at).toLocaleDateString("pt-BR")}`:"Sem link ativo"}<small>{accesses} acesso(s){token?.last_access_at?` · último ${new Date(token.last_access_at).toLocaleDateString("pt-BR")}`:""}</small></span><div><button onClick={()=>createLink(c.id)}>{token?"Renovar link":"Gerar link"}</button>{token&&<button onClick={()=>navigator.clipboard.writeText(`${location.origin}/cliente/${token.token}`)}>Copiar</button>}{token&&<button onClick={()=>window.open(`/cliente/${token.token}`,"_blank","noopener,noreferrer")}>Abrir</button>}{token&&<button className="danger-button" onClick={()=>revoke(token.id)}>Revogar</button>}</div></article>})}{!signed.length&&<p>Nenhum contrato assinado disponível.</p>}</div></section>}
