"use client";

import { useCallback, useEffect, useState } from "react";
import { client, errorText } from "./chat-client";
import { workspaceCall } from "./workspace-client";
import styles from "./workspace.module.css";

type Status={enabled?:boolean;ready?:boolean;mode?:string;display_phone_number?:string;phone_number_id?:string;graph_api_version?:string};
type Template={name:string;language:string;category?:string;components?:unknown[]};
export default function ArisaWhatsAppPanel({organizationId}:{organizationId:string}){
  const [status,setStatus]=useState<Status|null>(null),[templates,setTemplates]=useState<Template[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const refresh=useCallback(async()=>{try{const data=await workspaceCall("arisa-whatsapp",{action:"status",organizationId});setStatus(data);}catch(e){setError(errorText(e));}},[organizationId]);
  useEffect(()=>{void refresh();},[refresh]);
  async function activate(enabled:boolean){setBusy(true);setError("");setNotice("");try{const result=await client().rpc("configure_whatsapp_runtime",{p_organization_id:organizationId,p_enabled:enabled});if(result.error)throw result.error;setNotice(enabled?"Canal WhatsApp ativado para a Arisa.":"Canal WhatsApp pausado. O histórico foi preservado.");await refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function loadTemplates(){setBusy(true);setError("");try{const data=await workspaceCall("arisa-whatsapp",{action:"templates",organizationId});setTemplates(data.templates||[]);setNotice(`${data.count||0} template(s) aprovado(s) encontrado(s) na Meta.`);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <section className={styles.card} aria-labelledby="arisa-whatsapp-title"><div className={styles.meta}>WHATSAPP BUSINESS PLATFORM</div><h3 id="arisa-whatsapp-title">WhatsApp da Arisa</h3><p>{!status?"Verificando o canal…":status.ready?`Canal ativo${status.display_phone_number?` em ${status.display_phone_number}`:""}. A Arisa pode iniciar e continuar conversas pelas regras oficiais da Meta.`:"A infraestrutura está cadastrada, mas o canal ainda precisa estar ativo para enviar e receber mensagens."}</p><p><small>Dentro de 24 horas da última mensagem recebida, a Arisa pode escrever texto livre. Fora dessa janela, a primeira mensagem precisa usar um template aprovado pela Meta. Opt-out e bloqueios do cadastro são respeitados.</small></p><div className={styles.row}>{status?.enabled?<button disabled={busy} onClick={()=>void activate(false)}>Pausar canal</button>:<button className={styles.primary} disabled={busy} onClick={()=>void activate(true)}>Ativar WhatsApp</button>}<button disabled={busy||!status?.enabled} onClick={()=>void loadTemplates()}>Consultar templates aprovados</button></div>{notice&&<p role="status" className={styles.notice}>{notice}</p>}{error&&<p role="alert" className={styles.error}>{error}</p>}{templates.length>0&&<details open><summary>Templates aprovados ({templates.length})</summary><ul>{templates.map(item=><li key={`${item.name}:${item.language}`}><strong>{item.name}</strong> · {item.language}{item.category?` · ${item.category}`:""}</li>)}</ul></details>}<details><summary>Configuração técnica do webhook</summary><p>O recebimento e os status de enviado/entregue/lido usam o webhook oficial já existente da Évora. A URL deve estar cadastrada no aplicativo Meta junto com o token de verificação da conexão.</p><label>Callback URL<input readOnly value={`https://qsdffayasuzsmngteika.supabase.co/functions/v1/enterprise-whatsapp-webhook?organizationId=${organizationId}`} onFocus={e=>e.target.select()} /></label><small>As credenciais permanecem no cofre do servidor e não são exibidas nesta tela.</small></details><p><small>Você pode pedir no chat: “Arisa, avise o fornecedor pelo WhatsApp”. A Arisa resolve o contato, verifica a janela, usa template quando necessário e registra o envio no histórico.</small></p></section>;
}
