import type {Metadata,Viewport} from "next";
import "./globals.css";
import "./styles/v5-4-layout.css";
import "./styles/v5-4-admin.css";
import "./styles/v5-5-governance.css";
import "./styles/v5-6-signatures.css";
import "./styles/v5-7-backup.css";
import "./styles/v5-8-experience.css";
import "./styles/v6-0-marketing-dre-portal.css";
import "./styles/v6-0-signatures.css";
import "./styles/v6-1-otp-simulation.css";
import "./styles/v6-2-payment-decisions.css";
import "./styles/v6-3-assets-help.css";
import "./styles/v6-4-contract-portal.css";
import "./styles/v6-5-activities-notifications.css";
import "./styles/v6-5-1-session.css";
import "./styles/v6-6-operations.css";
import "./styles/v6-6-eap.css";
import "./styles/v6-6-responsive-fixes.css";
import "./styles/v6-7-post-sale-work-sync.css";
import "./styles/v6-8-buyer-portal-work.css";
import "./styles/v6-7-permissions.css";
import "./styles/v6-9-decision-intelligence.css";
import "./styles/v6-10-partner-payments.css";
import "./styles/v6-10-agenda-actionability.css";
import "./styles/v6-10-payment-scheduling.css";
import "./styles/v6-11-finance-landowners.css";
import {ServiceWorkerRegister} from "@/components/ServiceWorkerRegister";
import {GlobalModuleNav} from "@/components/GlobalModuleNav";
import {GlobalLogoutButton} from "@/components/GlobalLogoutButton";
import {HelpMenuShortcutV63} from "@/components/erp/help/help-menu-shortcut-v63";
export const metadata:Metadata={title:"Évora Gestão — Versão 6.17 Enterprise",description:"Plataforma integrada da Évora Urbanismo com portal seguro de parceiros e pagamentos, negociação com credores, obras, combustíveis, contratos, agenda, financeiro, CRM, pós-venda e governança.",manifest:"/manifest.webmanifest",applicationName:"Évora Gestão",icons:{icon:"/icon.svg",apple:"/icon.svg"},appleWebApp:{capable:true,statusBarStyle:"default",title:"Évora Gestão"}};
export const viewport:Viewport={width:"device-width",initialScale:1,maximumScale:1,viewportFit:"cover",themeColor:"#1D5271"};
export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){return <html lang="pt-BR"><body><ServiceWorkerRegister/><GlobalModuleNav/><HelpMenuShortcutV63/><GlobalLogoutButton/>{children}</body></html>}
