import type {Metadata,Viewport} from "next";
import "./globals.css";
import "./styles/v5-4-layout.css";
import "./styles/v5-4-admin.css";
import "./styles/v5-5-governance.css";
import "./styles/v5-6-signatures.css";
import "./styles/v5-7-backup.css";
import "./styles/v5-8-experience.css";
import "./styles/v6-0-marketing-dre-portal.css";
import "./styles/v6-0-signatures.css";
import "./styles/v6-1-otp-simulation.css";
import "./styles/v6-2-payment-decisions.css";
import "./styles/v6-3-assets-help.css";
import "./styles/v6-4-contract-portal.css";
import "./styles/v6-5-activities-notifications.css";
import "./styles/v6-5-1-session.css";
import {ServiceWorkerRegister} from "@/components/ServiceWorkerRegister";
import {GlobalModuleNav} from "@/components/GlobalModuleNav";
import {GlobalLogoutButton} from "@/components/GlobalLogoutButton";
import {HelpMenuShortcutV63} from "@/components/erp/help/help-menu-shortcut-v63";
export const metadata:Metadata={title:"Évora Gestão — Versão 6.5.1 Enterprise",description:"Plataforma integrada da Évora Urbanismo com agenda colaborativa, notificações de designação e atraso, cancelamento de propostas e contratos não assinados, assinatura eletrônica simplificada, logout seguro, Portal do Consumidor, DRE gerencial, CRM, pós-venda e governança.",manifest:"/manifest.webmanifest",applicationName:"Évora Gestão",icons:{icon:"/icon.svg",apple:"/icon.svg"},appleWebApp:{capable:true,statusBarStyle:"default",title:"Évora Gestão"}};
export const viewport:Viewport={width:"device-width",initialScale:1,maximumScale:1,viewportFit:"cover",themeColor:"#1D5271"};
export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){return <html lang="pt-BR"><body><ServiceWorkerRegister/><GlobalModuleNav/><HelpMenuShortcutV63/><GlobalLogoutButton/>{children}</body></html>}
