"use client";
import {useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData} from "../../types";
import {canAdmin} from "../../utils";
import type {SalesData,SalesProposal} from "./types";
import {brl,escapeHtml,openPrintDocument,proposalSnapshot,statusLabel} from "./utils";
import {ProposalModal} from "./proposal-modal";

export function ProposalsViewV56({data,sales,reload}:{data:ErpData;sales:SalesData;reload:()=>Promise<void>}){const[show,setShow]=useState(false),[initialUnit,setInitialUnit]=useState<string|undefined>(),[filter,setFilter]=useState("");useEffect(()=>{const stored=localStorage.getItem("evora-proposal-unit");if(stored){setInitialUnit(stored);setShow(true);localStorage.removeItem("evora-proposal-unit")}},[]);const rows=sales.proposals.filter(p=>!filter||p.status===filter);
async function approve(p:SalesProposal){const client=getSupabase();if(!client)return;const r=await client.from("crm_proposals").update({status:"aprovada",approval_status:"aprovada",approved_by:data.session.user.id,approved_at:new Date().toISOString()}).eq("id",p.id);if(r.error)throw r.error;await client.from("crm_proposal_approvals").update({status:"aprovada",decided_at:new Date().toISOString(),decision_notes:"Aprovada no CRM"}).eq("proposal_id",p.id).eq("status","pendente");await reload()}
async function reject(p:SalesProposal){const reason=prompt("Motivo da rejeição:");if(!reason)return;const client=getSupabase();if(!client)return;const r=await client.from("crm_proposals").update({status:"rejeitada",approval_status:"rejeitada",rejection_reason:reason}).eq("id",p.id);if(r.error)throw r.error;await client.from("crm_proposal_approvals").update({status:"rejeitada",decided_at:new Date().toISOString(),decision_notes:reason}).eq("proposal_id",p.id).eq("status","pendente");await reload()}
async function createShare(p:SalesProposal){const client=getSupabase();if(!client)throw new Error("Supabase indisponível");const unit=sales.units.find(u=>u.id===p.unit_id),project=data.projects.find(x=>x.id===p.project_id);if(!unit||!project)throw new Error("Dados da proposta incompletos");const installments=sales.installments.filter(i=>i.proposal_id===p.id),snapshot=proposalSnapshot(p,unit,project,data.organization,installments);const r=await client.from("crm_proposal_public_snapshots").upsert({token:p.public_token,proposal_id:p.id,snapshot,active:true,expires_at:p.valid_until||new Date(Date.now()+5*86400000).toISOString()},{onConflict:"proposal_id"});if(r.error)throw r.error;return `${location.origin}/proposta/${p.public_token}`}
async function logSend(p:SalesProposal,channel:"email"|"whatsapp"|"link",recipient:string,url:string){const client=getSupabase();if(!client)return;const r=await client.from("crm_proposal_communications").insert({organization_id:data.organization.id,proposal_id:p.id,channel,recipient,subject:`Proposta ${p.proposal_number}`,message:`Proposta comercial ${p.proposal_number} com aceite eletrônico`,status:"enviada",share_url:url,sent_by:data.session.user.id,sent_at:new Date().toISOString()});if(r.error)throw r.error;await client.from("crm_proposals").update({status:"enviada",sent_at:new Date().toISOString()}).eq("id",p.id)}
async function share(p:SalesProposal,channel:"email"|"whatsapp"|"link"){const url=await createShare(p);if(channel==="link"){await navigator.clipboard.writeText(url);await logSend(p,"link","",url);alert("Link de aceite copiado.")}else if(channel==="whatsapp"){const phone=(p.customer_phone||"").replace(/\D/g,"");const text=encodeURIComponent(`Olá, ${p.customer_name}. Acesse e aceite eletronicamente a proposta ${p.proposal_number} da Évora Urbanismo: ${url}`);await logSend(p,"whatsapp",phone,url);window.open(`https://wa.me/${phone}?text=${text}`,"_blank")}else{const subject=encodeURIComponent(`Proposta comercial ${p.proposal_number} — Évora Urbanismo`);const body=encodeURIComponent(`Olá, ${p.customer_name}.\n\nAcesse, confira e aceite eletronicamente sua proposta: ${url}\n\nApós o aceite, o contrato será gerado automaticamente.\n\nÉvora Urbanismo`);await logSend(p,"email",p.customer_email||"",url);location.href=`mailto:${p.customer_email||""}?subject=${subject}&body=${body}`}await reload()}
function printProposal(p:SalesProposal){const unit=sales.units.find(u=>u.id===p.unit_id),project=data.projects.find(x=>x.id===p.project_id),installments=sales.installments.filter(i=>i.proposal_id===p.id);if(!unit||!project)return;const body=`<header><img src="${location.origin}/evora-brand.svg" style="width:260px"><h1>Proposta comercial ${escapeHtml(p.proposal_number)}</h1><p class="muted">${escapeHtml(project.name)} · Unidade ${escapeHtml(unit.unit_code)}</p></header><h2>Cliente</h2><p><strong>${escapeHtml(p.customer_name)}</strong><br>${escapeHtml(p.customer_email||"")} · ${escapeHtml(p.customer_phone||"")}</p><h2>Condição comercial</h2><table><tr><th>Preço de tabela</th><td>${brl.format(Number(p.list_price))}</td><th>Preço proposto</th><td class="total">${brl.format(Number(p.sale_price))}</td></tr><tr><th>Entrada</th><td>${brl.format(Number(p.down_payment))}</td><th>Saldo financiado</th><td>${brl.format(Number(p.financed_amount))}</td></tr><tr><th>Prazo</th><td>${p.installments_count} meses</td><th>Atualização</th><td>${(Number(p.monthly_interest_rate)*100).toFixed(3)}% a.m. + ${escapeHtml(p.indexer||"")}</td></tr></table><h2>Plano de pagamento</h2><table><tr><th>#</th><th>Tipo</th><th>Vencimento</th><th>Valor</th></tr>${installments.map(i=>`<tr><td>${i.installment_number}</td><td>${i.installment_type}</td><td>${new Date(`${i.due_date}T12:00:00`).toLocaleDateString("pt-BR")}</td><td>${brl.format(Number(i.amount))}</td></tr>`).join("")}</table><p>${escapeHtml(p.conditions_text||"")}</p><p class="muted">O aceite válido ocorre exclusivamente pelo link eletrônico da proposta e gera automaticamente o contrato.</p>`;openPrintDocument(`Proposta ${p.proposal_number}`,body)}
return <div className="crm5-stack"><section className="crm5-section-header"><div><small>PROPOSTAS E ACEITE ELETRÔNICO</small><h2>Propostas comerciais</h2><p>Aprovação, PDF, envio, aceite auditável e geração automática do contrato.</p></div><div className="toolbar-actions"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos os status</option>{["rascunho","submetida","aprovada","rejeitada","enviada","aceita","contratada"].map(v=><option key={v} value={v}>{statusLabel[v]}</option>)}</select><button className="primary" onClick={()=>{setInitialUnit(undefined);setShow(true)}}>+ Nova proposta</button></div></section><section className="proposal-list">{rows.map(p=>{const unit=sales.units.find(u=>u.id===p.unit_id),contract=sales.contracts.find(c=>c.proposal_id===p.id);return <article key={p.id}><header><div><small>{p.proposal_number}</small><h3>{p.customer_name}</h3><span>{data.projects.find(x=>x.id===p.project_id)?.name} · {unit?.unit_code}</span></div><i data-status={p.status}>{statusLabel[p.status]||p.status}</i></header><div className="proposal-values"><span><small>Tabela</small>{brl.format(Number(p.list_price))}</span><span><small>Proposta</small><strong>{brl.format(Number(p.sale_price))}</strong></span><span><small>Entrada</small>{brl.format(Number(p.down_payment))}</span><span><small>Prazo</small>{p.installments_count} meses</span><span><small>Formalização</small>{p.status==="aceita"||p.status==="contratada"?"Aceite eletrônico":"Aguardando"}</span></div>{p.rejection_reason&&<p className="feedback error">{p.rejection_reason}</p>}{contract&&<div className="feedback">Contrato {contract.contract_number} gerado automaticamente.</div>}<footer><button onClick={()=>printProposal(p)}>Gerar PDF</button>{p.approval_status==="pendente"&&canAdmin(data.membership.role)&&<><button className="primary" onClick={()=>approve(p)}>Aprovar</button><button onClick={()=>reject(p)}>Rejeitar</button></>}{["aprovada","enviada"].includes(p.status)&&<><button onClick={()=>share(p,"link")}>Copiar link de aceite</button><button onClick={()=>share(p,"whatsapp")}>WhatsApp</button><button onClick={()=>share(p,"email")}>E-mail</button></>}</footer></article>})}{!rows.length&&<div className="crm5-empty"><strong>Nenhuma proposta encontrada</strong><p>Crie uma proposta a partir do mapa de vendas ou deste módulo.</p></div>}</section>{show&&<ProposalModal data={data} sales={sales} initialUnitId={initialUnit} close={()=>setShow(false)} reload={reload}/>}</div>}
