export type InventoryStatus = "disponivel" | "reservado" | "vendido" | "bloqueio_estrategico" | "bloqueio_comercial" | "indisponivel";
export interface InventoryUnit { id:string; organization_id:string; project_id:string; block_code:string; lot_number:string; unit_code:string; unit_type:string; area:number; frontage:number|null; depth:number|null; corner:boolean; topography:string|null; orientation:string|null; status:InventoryStatus; list_price:number; price_per_sqm:number|null; minimum_price:number|null; strategic_reason:string|null; reserved_until:string|null; map_x:number|null; map_y:number|null; map_width:number|null; map_height:number|null; polygon:unknown[]; attributes:Record<string,unknown>; active:boolean; created_at:string; updated_at:string; }
export interface NegotiationPolicy { id:string; organization_id:string; project_id:string; name:string; active:boolean; valid_from:string|null; valid_until:string|null; min_down_payment_pct:number; max_discount_pct:number; admin_approval_discount_pct:number; max_installments:number; min_installment:number; monthly_interest_rate:number; indexer:string; grace_months:number; balloon_limit_pct:number; balloon_frequency_months:number; proposal_validity_days:number; reservation_validity_hours:number; require_admin_below_min_price:boolean; allow_custom_schedule:boolean; parameters:Record<string,unknown>; }
export interface UnitReservation { id:string; organization_id:string; project_id:string; unit_id:string; crm_record_id:string|null; contact_id:string|null; customer_name:string; reservation_type:"comercial"|"estrategica"; status:"ativa"|"expirada"|"cancelada"|"convertida"; starts_at:string; expires_at:string|null; reservation_fee:number; payment_status:string; notes:string|null; created_by:string|null; approved_by:string|null; created_at:string; updated_at:string; }
export interface SalesProposal { id:string; organization_id:string; project_id:string; unit_id:string; crm_record_id:string|null; contact_id:string|null; reservation_id:string|null; proposal_number:string; public_token:string; customer_name:string; customer_document:string|null; customer_email:string|null; customer_phone:string|null; customer_address:Record<string,unknown>; status:"rascunho"|"submetida"|"aprovada"|"rejeitada"|"enviada"|"aceita"|"recusada"|"expirada"|"cancelada"|"contratada"; approval_status:"nao_solicitada"|"pendente"|"aprovada"|"rejeitada"; list_price:number; discount_pct:number; discount_amount:number; sale_price:number; down_payment:number; financed_amount:number; installments_count:number; monthly_interest_rate:number; indexer:string|null; grace_months:number; balloon_total:number; payment_plan:Array<Record<string,unknown>>; conditions_text:string|null; valid_until:string|null; requires_approval:boolean; submitted_at:string|null; approved_by:string|null; approved_at:string|null; rejection_reason:string|null; sent_at:string|null; accepted_at:string|null; declined_at:string|null; pdf_path:string|null; created_by:string|null; created_at:string; updated_at:string; }
export interface ProposalApproval { id:string; organization_id:string; proposal_id:string; requested_by:string; assigned_to:string|null; status:"pendente"|"aprovada"|"rejeitada"|"cancelada"; reason:string|null; decision_notes:string|null; snapshot:Record<string,unknown>; created_at:string; decided_at:string|null; }
export interface ProposalInstallment { id:string; organization_id:string; proposal_id:string; installment_number:number; installment_type:"entrada"|"mensal"|"balao"|"reforco"|"taxa"; due_date:string; amount:number; status:"planejada"|"emitida"|"paga"|"cancelada"; financial_entry_id:string|null; created_at:string; }
export interface SalesContract { id:string; organization_id:string; project_id:string; proposal_id:string; unit_id:string; contact_id:string|null; contract_number:string; status:"rascunho"|"gerado"|"enviado"|"assinado"|"cancelado"; template_key:string; contract_data:Record<string,unknown>; document_path:string|null; generated_at:string|null; sent_at:string|null; signed_at:string|null; signed_by:string|null; created_by:string|null; created_at:string; updated_at:string; }
export interface ContractTemplate { id:string; organization_id:string; project_id:string|null; name:string; template_key:string; title:string; body:string; clauses:Array<{title:string;text:string}>; active:boolean; }
export interface ProposalCommunication { id:string; organization_id:string; proposal_id:string|null; contract_id:string|null; channel:"email"|"whatsapp"|"link"|"sistema"; recipient:string|null; subject:string|null; message:string|null; status:string; share_url:string|null; sent_by:string|null; sent_at:string|null; created_at:string; }
export interface ProposalSnapshot { token:string; proposal_id:string; snapshot:Record<string,unknown>; active:boolean; expires_at:string; }
export interface SalesData { units:InventoryUnit[]; policies:NegotiationPolicy[]; reservations:UnitReservation[]; proposals:SalesProposal[]; approvals:ProposalApproval[]; installments:ProposalInstallment[]; contracts:SalesContract[]; templates:ContractTemplate[]; communications:ProposalCommunication[]; snapshots:ProposalSnapshot[]; }
