import type {InventoryUnit,NegotiationPolicy,ProposalInstallment,SalesProposal} from "./types";
export const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
export const statusLabel:Record<string,string>={disponivel:"Disponível",reservado:"Reservado",vendido:"Vendido",bloqueio_estrategico:"Bloqueio estratégico",bloqueio_comercial:"Bloqueio comercial",indisponivel:"Indisponível",rascunho:"Rascunho",submetida:"Em aprovação",aprovada:"Aprovada",rejeitada:"Rejeitada",enviada:"Enviada",aceita:"Aceita",recusada:"Recusada",expirada:"Expirada",cancelada:"Cancelada",contratada:"Contratada",gerado:"Gerado",assinado:"Assinado"};
export function addMonths(date:Date,months:number){const d=new Date(date);d.setMonth(d.getMonth()+months);return d.toISOString().slice(0,10)}
export function buildPlan(input:{salePrice:number;downPayment:number;installments:number;monthlyRate:number;graceMonths:number;balloonTotal:number;balloonCount:number;balloonFrequency:number;firstDueDate:string}){const rows:Array<{installment_number:number;installment_type:"entrada"|"mensal"|"balao";due_date:string;amount:number}>=[];let number=1;if(input.downPayment>0)rows.push({installment_number:number++,installment_type:"entrada",due_date:new Date().toISOString().slice(0,10),amount:round(input.downPayment)});const balloonCount=Math.max(0,input.balloonCount||0);const eachBalloon=balloonCount?input.balloonTotal/balloonCount:0;const principal=Math.max(0,input.salePrice-input.downPayment-input.balloonTotal);const n=Math.max(0,input.installments||0);const r=Math.max(0,input.monthlyRate||0);const monthly=n?(r>0?principal*(r*Math.pow(1+r,n))/(Math.pow(1+r,n)-1):principal/n):0;const start=new Date(`${input.firstDueDate}T12:00:00`);for(let i=0;i<n;i++)rows.push({installment_number:number++,installment_type:"mensal",due_date:addMonths(start,i+input.graceMonths),amount:round(monthly)});for(let i=1;i<=balloonCount;i++)rows.push({installment_number:number++,installment_type:"balao",due_date:addMonths(start,i*input.balloonFrequency),amount:round(eachBalloon)});return rows.sort((a,b)=>a.due_date.localeCompare(b.due_date)||a.installment_number-b.installment_number).map((r,i)=>({...r,installment_number:i+1}));}
export function proposalCompliance(unit:InventoryUnit,policy:NegotiationPolicy|undefined,input:{salePrice:number;downPayment:number;installments:number;balloonTotal:number}){if(!policy)return{requiresApproval:false,reasons:[] as string[]};const reasons:string[]=[];const discount=unit.list_price>0?(unit.list_price-input.salePrice)/unit.list_price:0;const down=input.salePrice>0?input.downPayment/input.salePrice:0;if(discount>policy.admin_approval_discount_pct)reasons.push(`Desconto acima de ${(policy.admin_approval_discount_pct*100).toFixed(1)}%`);if(discount>policy.max_discount_pct)reasons.push("Desconto superior ao limite comercial");if(down<policy.min_down_payment_pct)reasons.push("Entrada inferior ao mínimo");if(input.installments>policy.max_installments)reasons.push("Prazo superior ao permitido");if(input.balloonTotal>input.salePrice*policy.balloon_limit_pct)reasons.push("Balões acima do limite");if(unit.minimum_price&&input.salePrice<unit.minimum_price)reasons.push("Preço abaixo do mínimo da unidade");return{requiresApproval:reasons.length>0,reasons};}
export function proposalSnapshot(proposal:SalesProposal,unit:InventoryUnit,project:{name:string;city:string|null;state:string|null},organization:{name:string;trade_name:string|null},installments:ProposalInstallment[]){return{proposal:{number:proposal.proposal_number,customer_name:proposal.customer_name,status:proposal.status,list_price:proposal.list_price,discount_amount:proposal.discount_amount,sale_price:proposal.sale_price,down_payment:proposal.down_payment,financed_amount:proposal.financed_amount,installments_count:proposal.installments_count,monthly_interest_rate:proposal.monthly_interest_rate,indexer:proposal.indexer,valid_until:proposal.valid_until,conditions_text:proposal.conditions_text},unit:{code:unit.unit_code,block:unit.block_code,lot:unit.lot_number,area:unit.area,type:unit.unit_type,corner:unit.corner},project,organization,installments:installments.map(i=>({number:i.installment_number,type:i.installment_type,due_date:i.due_date,amount:i.amount}))};}
export function openPrintDocument(title:string,body:string){const win=window.open("","_blank","width=980,height=900");if(!win)return;win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>body{font:14px Arial;color:#17364a;margin:36px}header{border-bottom:4px solid #79b82b;padding-bottom:18px;margin-bottom:24px}h1{color:#1d5271}table{width:100%;border-collapse:collapse;margin:18px 0}td,th{border:1px solid #d7e0e5;padding:8px;text-align:left}.total{font-size:20px;font-weight:700;color:#1d5271}.muted{color:#6b7880}.signature{margin-top:70px;display:grid;grid-template-columns:1fr 1fr;gap:50px}.signature div{border-top:1px solid #333;padding-top:8px;text-align:center}@media print{button{display:none}}</style></head><body>${body}<button onclick="window.print()">Imprimir ou salvar em PDF</button></body></html>`);win.document.close();}
export function escapeHtml(value:unknown){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]||c))}
function round(v:number){return Math.round((v+Number.EPSILON)*100)/100}
