"use client";
import {FormEvent,useMemo,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData,PurchaseRequest} from "../types";
import {analyzeComprehensivePaymentRisk} from "../operational-cash";
import {dateAtNoon,money,shortDate} from "../utils";
import {PanelTitle} from "../views-dashboard";
type ExtendedPurchase=PurchaseRequest&{negotiated_payment_date?:string|null;decision_notes?:string|null;decided_at?:string|null;decided_by?:string|null};
export function PurchaseDecisionModal({data,request,decision,close,mutate}:{data:ErpData;request:ExtendedPurchase;decision:"aprovada"|"rejeitada";close:()=>void;mutate:(operation:()=>Promise<void>,success:string)=>Promise<void>}){
 const originalDate=request.payment_due_date||new Date().toISOString().slice(0,10);
 const originalRisk=useMemo(()=>analyzeComprehensivePaymentRisk(data,{amount:Number(request.estimated_total),dueDate:originalDate}),[data,request,originalDate]);
 const suggested=request.recommended_payment_date||originalRisk.recommendedDate||originalDate;
 const[date,setDate]=useState(suggested),[note,setNote]=useState(decision==="aprovada"?"Condição e data de pagamento aprovadas pela administração.":"Solicitação rejeitada pela administração."),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const risk=useMemo(()=>analyzeComprehensivePaymentRisk(data,{amount:Number(request.estimated_total),dueDate:date}),[data,request,date]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await mutate(async()=>{const s=getSupabase();if(!s)throw new Error("Supabase indisponível.");const now=new Date().toISOString();const payload:any={status:decision,negotiated_payment_date:date,decision_notes:note,decided_at:now,decided_by:data.session.user.id,recommended_payment_date:originalRisk.recommendedDate||request.recommended_payment_date||null,cash_risk:risk.risky,cash_risk_level:risk.level,projected_balance:risk.projectedBalance,approved_by:decision==="aprovada"?data.session.user.id:null,approved_at:decision==="aprovada"?now:null,rejection_reason:decision==="rejeitada"?note:null};if(decision==="aprovada")payload.payment_due_date=date;const r=await s.from("purchase_requests").update(payload).eq("id",request.id);if(r.error)throw new Error(r.error.message)},decision==="aprovada"?"Compra aprovada com data de pagamento definida.":"Solicitação rejeitada e negociação registrada.");close()}catch(err){setError(err instanceof Error?err.message:"Não foi possível registrar a decisão.")}finally{setBusy(false)}}
 return <div className="modal-backdrop" onMouseDown={close}><form className="modal payment-decision-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><PanelTitle eyebrow="DECISÃO DE COMPRA" title={decision==="aprovada"?"Aprovar contratação e pagamento":"Rejeitar solicitação"}/><button type="button" className="modal-close" onClick={close}>×</button><section className="decision-summary"><article><small>Solicitação</small><strong>{request.title}</strong><span>{money.format(Number(request.estimated_total))}</span></article><article><small>Pagamento solicitado</small><strong>{shortDate.format(dateAtNoon(originalDate))}</strong></article><article><small>Primeira data com cobertura</small><strong>{originalRisk.recommendedDate?shortDate.format(dateAtNoon(originalRisk.recommendedDate)):originalRisk.risky?"Sem cobertura no horizonte":"Data original compatível"}</strong></article></section><label>{decision==="aprovada"?"Data aprovada / negociada com o fornecedor":"Data negociada para registro"}<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><div className={`cash-risk-alert ${risk.level}`}><div><b>{risk.risky?"!":"✓"}</b><span><strong>{risk.risky?"A data selecionada mantém risco de caixa":"A data selecionada possui cobertura"}</strong><small>Saldo após o compromisso: {money.format(risk.projectedBalance)}</small></span></div><p>{risk.reason}</p>{risk.recommendedDate&&risk.recommendedDate!==date&&<button type="button" onClick={()=>setDate(risk.recommendedDate!)}>Aplicar data recomendada: {shortDate.format(dateAtNoon(risk.recommendedDate))}</button>}</div><label>Justificativa, prazo e condições negociadas<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} required/></label>{error&&<div className="feedback error">{error}</div>}<footer><button type="button" onClick={close}>Cancelar</button><button className={decision==="aprovada"?"primary":"danger"} disabled={busy}>{busy?"Registrando...":decision==="aprovada"?"Aprovar nesta data":"Confirmar rejeição"}</button></footer></form></div>}
