"use client";
import { FormEvent } from "react";
import { getSupabase } from "@/lib/supabase";
import type { AdminProps } from "./views-admin";
import { PanelTitle } from "./views-dashboard";

export function SettingsView({ data, mutate }: AdminProps) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await mutate(async () => { const supabase = getSupabase(); if (!supabase) throw new Error("Supabase indisponível."); const { error } = await supabase.from("system_settings").upsert({ organization_id:data.organization.id, approval_threshold:Number(form.get("approval_threshold")), require_approval:form.get("require_approval") === "on", default_due_alert_days:Number(form.get("default_due_alert_days")) }); if (error) throw new Error(error.message); }, "Configurações atualizadas."); }
  return <div className="settings-layout"><form className="panel" onSubmit={submit}><PanelTitle eyebrow="POLÍTICAS FINANCEIRAS" title="Aprovações e alertas" /><label>Valor mínimo para aprovação<input name="approval_threshold" type="number" step="0.01" defaultValue={data.settings.approval_threshold} /></label><label>Dias de antecedência para alertas<input name="default_due_alert_days" type="number" min="1" defaultValue={data.settings.default_due_alert_days} /></label><label className="switch"><input name="require_approval" type="checkbox" defaultChecked={data.settings.require_approval} /><span /> Exigir aprovação acima da alçada</label><button className="primary">Salvar configurações</button></form><section className="panel"><PanelTitle eyebrow="ORGANIZAÇÃO" title="Dados corporativos" /><dl className="org-data"><div><dt>Razão social</dt><dd>{data.organization.name}</dd></div><div><dt>Nome de exibição</dt><dd>{data.organization.trade_name || "—"}</dd></div><div><dt>Documento</dt><dd>{data.organization.document || "Não informado"}</dd></div><div><dt>Moeda</dt><dd>{data.organization.currency}</dd></div></dl><div className="version-card"><strong>Évora Gestão ERP</strong><span>Versão 2.0 · Next.js + Supabase</span><small>Ambiente corporativo responsivo</small></div></section></div>;
}
