"use client";
import {FormEvent,useMemo,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ApprovalRequest,ErpData,FinancialEntry} from "./types";
import {analyzeComprehensivePaymentRisk} from "./operational-cash";
import {dateAtNoon,money,shortDate} from "./utils";
import {PanelTitle} from "./views-dashboard";
type ExtendedRequest=ApprovalRequest&{negotiated_due_date?:string|null};
type ExtendedEntry=FinancialEntry&{negotiated_due_date?:string|null;due_date_change_reason?:string|null};
export function ApprovalDecisionModal({data,request,entry,decision,close,mutate}:{data:ErpData;request:ExtendedRequest;entry:ExtendedEntry;decision:"aprovado"|"rejeitado";close:()=>void;mutate:(operation:()=>Promise<void>,success:string)=>Promise<void>}){
 const originalRisk=useMemo(()=>analyzeComprehensivePaymentRisk(data,{amount:Number(entry.amount),dueDate:entry.due_date,accountId:entry.bank_account_id,excludeEntryId:entry.id}),[data,entry]);
 const suggested=entry.recommended_due_date||request.recommended_due_date||originalRisk.recommendedDate||entry.due_date;
 const[date,setDate]=useState(suggested),[note,setNote]=useState(decision==="aprovado"?"Data analisada e aprovada pela administração.":"Pagamento rejeitado pela administração."),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const risk=useMemo(()=>analyzeComprehensivePaymentRisk(data,{amount:Number(entry.amount),dueDate:date,accountId:entry.bank_account_id,excludeEntryId:entry.id}),[data,entry,date]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await mutate(async()=>{const s=getSupabase();if(!s)throw new Error("Supabase indisponível.");const now=new Date().toISOString();const requestUpdate={status:decision,decided_at:now,assigned_to:data.session.user.id,comment:note,negotiated_due_date:date,recommended_due_date:originalRisk.recommendedDate||entry.recommended_due_date||request.recommended_due_date||null};const entryUpdate:any={approval_status:decision,approved_by:decision==="aprovado"?data.session.user.id:null,approved_at:decision==="aprovado"?now:null,negotiated_due_date:date,due_date_change_reason:note,cash_risk:risk.risky,cash_risk_level:risk.level,projected_balance:risk.projectedBalance,recommended_due_date:risk.recommendedDate,risk_reason:risk.reason};if(decision==="aprovado")entryUpdate.due_date=date;const[r1,r2]=await Promise.all([s.from("approval_requests").update(requestUpdate).eq("id",request.id),s.from("financial_entries").update(entryUpdate).eq("id",entry.id)]);if(r1.error)throw new Error(r1.error.message);if(r2.error)throw new Error(r2.error.message)},decision==="aprovado"?"Pagamento aprovado com data definida.":"Pagamento rejeitado e decisão registrada.");close()}catch(err){setError(err instanceof Error?err.message:"Não foi possível registrar a decisão.")}finally{setBusy(false)}}
 return <div className="modal-backdrop" onMouseDown={close}><form className="modal payment-decision-modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><PanelTitle eyebrow="DECISÃO FINANCEIRA" title={decision==="aprovado"?"Aprovar e definir pagamento":"Rejeitar e registrar negociação"}/><button type="button" className="modal-close" onClick={close}>×</button><section className="decision-summary"><article><small>Compromisso</small><strong>{entry.description}</strong><span>{money.format(Number(entry.amount))}</span></article><article><small>Data originalmente solicitada</small><strong>{shortDate.format(dateAtNoon(entry.due_date))}</strong></article><article><small>Primeira data com cobertura</small><strong>{originalRisk.recommendedDate?shortDate.format(dateAtNoon(originalRisk.recommendedDate)):originalRisk.risky?"Sem cobertura no horizonte":"Data original compatível"}</strong></article></section><label>{decision==="aprovado"?"Data aprovada / negociada":"Data negociada para registro"}<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><div className={`cash-risk-alert ${risk.level}`}><div><b>{risk.risky?"!":"✓"}</b><span><strong>{risk.risky?"A data escolhida ainda exige exceção":"Data compatível com o caixa projetado"}</strong><small>Saldo após o pagamento: {money.format(risk.projectedBalance)}</small></span></div><p>{risk.reason}</p>{risk.recommendedDate&&risk.recommendedDate!==date&&<button type="button" onClick={()=>setDate(risk.recommendedDate!)}>Aplicar data recomendada: {shortDate.format(dateAtNoon(risk.recommendedDate))}</button>}</div><label>Justificativa e condições negociadas<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} required/></label>{error&&<div className="feedback error">{error}</div>}<footer><button type="button" onClick={close}>Cancelar</button><button className={decision==="aprovado"?"primary":"danger"} disabled={busy}>{busy?"Registrando...":decision==="aprovado"?"Aprovar nesta data":"Confirmar rejeição"}</button></footer></form></div>}
