"use client";
import {useState} from "react";
import type {ApprovalRequest,FinancialEntry} from "./types";
import type {AdminProps} from "./views-admin";
import {dateAtNoon,money,shortDate} from "./utils";
import {Empty,Kpi,PanelTitle} from "./views-dashboard";
import {ApprovalDecisionModal} from "./admin-approval-decision-modal";
type Decision={request:ApprovalRequest;entry:FinancialEntry;decision:"aprovado"|"rejeitado"};
export function ApprovalsView({data,mutate}:AdminProps){
 const[selected,setSelected]=useState<Decision|null>(null),pending=data.approvals.filter(item=>item.status==="pendente"),cashRisk=pending.filter(item=>data.entries.find(entry=>entry.id===item.entry_id)?.cash_risk);
 return <div className="stack"><section className="kpi-grid four"><Kpi label="Pendentes" value={String(pending.length)} detail="Aguardando decisão" tone="warning"/><Kpi label="Risco de caixa" value={String(cashRisk.length)} detail="Exigem atenção especial" tone="danger"/><Kpi label="Aprovadas" value={String(data.approvals.filter(item=>item.status==="aprovado").length)} detail="Histórico" tone="positive"/><Kpi label="Alçada automática" value={money.format(Number(data.settings.approval_threshold))} detail="Limite configurado" tone="gold"/></section><section className="panel"><PanelTitle eyebrow="ALÇADAS E EXCEÇÕES" title="Fila de aprovações"/>{pending.map(request=>{const entry=data.entries.find(item=>item.id===request.entry_id);if(!entry)return null;return <article className={`approval-row approval-row-v3 ${entry.cash_risk?"cash-risk":""}`} key={request.id}><div><span className={`movement-badge ${entry.type}`}>{entry.type==="entrada"?"↓":"↑"}</span><div><strong>{entry.description}</strong><small>{shortDate.format(dateAtNoon(entry.due_date))} · {data.costCenters.find(center=>center.id===entry.cost_center_id)?.name||data.categories.find(category=>category.id===entry.category_id)?.name||"Sem classificação"}</small>{(request.reason||entry.risk_reason)&&<p>{request.reason||entry.risk_reason}</p>}{entry.recommended_due_date&&<em>Data recomendada: {shortDate.format(dateAtNoon(entry.recommended_due_date))}</em>}</div></div><b>{money.format(Number(entry.amount))}</b><div><button onClick={()=>setSelected({request,entry,decision:"rejeitado"})}>Rejeitar</button><button className="primary" onClick={()=>setSelected({request,entry,decision:"aprovado"})}>Analisar e aprovar</button></div></article>})}{!pending.length&&<Empty text="Nenhuma aprovação pendente."/>}</section>{selected&&<ApprovalDecisionModal data={data} request={selected.request} entry={selected.entry} decision={selected.decision} close={()=>setSelected(null)} mutate={mutate}/>}</div>;
}
