"use client";
import { FormEvent, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import type { Role } from "./types";
import type { AdminProps } from "./views-admin";
import { roleLabels, shortDate } from "./utils";
import { Empty, PanelTitle } from "./views-dashboard";

export function UsersView({ data, mutate }: AdminProps) {
  const [invite, setInvite] = useState(false); const profileMap = new Map(data.profiles.map(p => [p.id, p]));
  const update = async (id: string, payload: Record<string, unknown>, success: string) => mutate(async () => { const supabase = getSupabase(); if (!supabase) throw new Error("Supabase indisponível."); const { error } = await supabase.from("organization_members").update(payload).eq("id", id); if (error) throw new Error(error.message); }, success);
  return <div className="stack"><section className="module-toolbar"><div><small>CONTROLE DE ACESSO</small><h2>Equipe e permissões</h2></div><button className="primary" onClick={() => setInvite(true)}>+ Convidar usuário</button></section><section className="panel"><PanelTitle eyebrow="USUÁRIOS ATIVOS" title="Membros da organização" /><div className="users-list">{data.members.map(member => { const profile = profileMap.get(member.user_id); return <article key={member.id}><span className="avatar-square">{(profile?.full_name || "US").slice(0, 2).toUpperCase()}</span><div><strong>{profile?.full_name || "Usuário cadastrado"}</strong><small>{member.user_id === data.session.user.id ? "Você · " : ""}{member.active ? "Acesso ativo" : "Acesso suspenso"}</small></div><select value={member.role} onChange={e => update(member.id, { role: e.target.value as Role }, "Perfil atualizado.")}>{Object.entries(roleLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><button onClick={() => update(member.id, { active: !member.active }, member.active ? "Acesso suspenso." : "Acesso reativado.")}>{member.active ? "Suspender" : "Reativar"}</button></article>; })}</div></section><section className="panel"><PanelTitle eyebrow="CONVITES" title="Acessos pendentes" /><div className="card-table">{data.invitations.map(item => <article key={item.id}><div className="avatar-square">✉</div><div><strong>{item.full_name || item.email}</strong><small>{item.email} · {roleLabels[item.role]}</small></div><span className={item.accepted_at ? "active-dot" : "inactive-dot"}>{item.accepted_at ? "Aceito" : "Pendente"}</span><div><small>Expira em {shortDate.format(new Date(item.expires_at))}</small></div></article>)}{!data.invitations.length && <Empty text="Nenhum convite enviado." />}</div></section>{invite && <InviteModal data={data} close={() => setInvite(false)} mutate={mutate} />}</div>;
}
function InviteModal({ data, close, mutate }: AdminProps & { close: () => void }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await mutate(async () => { const supabase = getSupabase(); if (!supabase) throw new Error("Supabase indisponível."); const { error } = await supabase.from("user_invitations").upsert({ organization_id: data.organization.id, email: String(form.get("email")).toLowerCase(), full_name: form.get("full_name"), role: form.get("role"), invited_by: data.session.user.id, accepted_at: null, expires_at: new Date(Date.now() + 14 * 86400000).toISOString() }, { onConflict: "organization_id,email" }); if (error) throw new Error(error.message); }, "Convite registrado."); close(); }
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={e => e.stopPropagation()}><PanelTitle eyebrow="NOVO ACESSO" title="Convidar usuário" /><button className="modal-close" type="button" onClick={close}>×</button><div className="form-grid"><label className="span-2">Nome completo<input name="full_name" required /></label><label className="span-2">E-mail<input name="email" type="email" required /></label><label className="span-2">Perfil<select name="role" defaultValue="consulta">{Object.entries(roleLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label></div><div className="info-box">O convite será vinculado ao e-mail informado.</div><footer><button type="button" onClick={close}>Cancelar</button><button className="primary">Registrar convite</button></footer></form></div>;
}
