"use client";
import { useMemo, useState } from "react";
import type { ErpData } from "./types";
import { downloadCsv, money } from "./utils";
import { Empty, PanelTitle } from "./views-dashboard";
export function ReportsView({ data }: { data: ErpData }) {
  const [kind,setKind]=useState("centro");
  const report=useMemo(()=>{const source=kind==="centro"?data.costCenters.map(x=>({id:x.id,label:`${x.code} · ${x.name}`,field:"cost_center_id" as const})):kind==="categoria"?data.categories.map(x=>({id:x.id,label:x.name,field:"category_id" as const})):data.projects.map(x=>({id:x.id,label:x.name,field:"project_id" as const}));return source.map(x=>({...x,entradas:data.entries.filter(e=>e[x.field]===x.id&&e.type==="entrada").reduce((s,e)=>s+Number(e.amount),0),saidas:data.entries.filter(e=>e[x.field]===x.id&&e.type==="saida").reduce((s,e)=>s+Number(e.amount),0)})).filter(x=>x.entradas||x.saidas).sort((a,b)=>(b.entradas+b.saidas)-(a.entradas+a.saidas));},[data,kind]);
  return <div className="stack"><section className="module-toolbar"><div><small>CONTROLADORIA</small><h2>Relatórios gerenciais</h2></div><div className="toolbar-actions"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="centro">Por centro de custo</option><option value="categoria">Por categoria</option><option value="projeto">Por empreendimento</option></select><button onClick={()=>downloadCsv(`relatorio-${kind}.csv`,["Classificação","Entradas","Saídas","Resultado"],report.map(x=>[x.label,x.entradas,x.saidas,x.entradas-x.saidas]))}>Exportar CSV</button><button onClick={()=>window.print()}>PDF / Imprimir</button></div></section><section className="panel"><PanelTitle eyebrow="ANÁLISE CONSOLIDADA" title={`Resultado por ${kind}`} /><div className="report-table"><header><span>Classificação</span><span>Entradas</span><span>Saídas</span><span>Resultado</span></header>{report.map(x=><article key={x.id}><strong>{x.label}</strong><span className="entrada">{money.format(x.entradas)}</span><span className="saida">{money.format(x.saidas)}</span><b>{money.format(x.entradas-x.saidas)}</b></article>)}{!report.length&&<Empty text="Ainda não há dados classificados."/>}</div></section></div>;
}
