"use client";

import { FormEvent } from "react";
import { getSupabase } from "@/lib/supabase";
import type { BankAccount, Category, Contact, CostCenter, ErpData, Project, RevenueCenter } from "./types";
import { CurrencyInput } from "./currency-input";
import { PanelTitle } from "./views-dashboard";

export type Entity = CostCenter | RevenueCenter | Category | BankAccount | Contact | Project;
export type EntityKind = "center" | "revenue" | "category" | "account" | "contact" | "project";

export function MasterModal({ kind, item, data, close, mutate }: { kind: EntityKind; item?: Entity; data: ErpData; close: () => void; mutate: (operation: () => Promise<void>, success: string) => Promise<void> }) {
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget); const organization_id = data.organization.id;
    const config: Record<EntityKind, { table: string; payload: Record<string, unknown> }> = {
      center: { table: "cost_centers", payload: { organization_id, code: form.get("code"), name: form.get("name"), center_type: form.get("center_type"), budget: form.get("budget") ? Number(form.get("budget")) : null, active: true } },
      revenue: { table: "revenue_centers", payload: { organization_id, code: form.get("code"), name: form.get("name"), center_type: form.get("center_type"), revenue_goal: form.get("revenue_goal") ? Number(form.get("revenue_goal")) : null, active: true } },
      category: { table: "financial_categories", payload: { organization_id, code: form.get("code"), name: form.get("name"), movement_type: form.get("movement_type"), active: true } },
      account: { table: "bank_accounts", payload: { organization_id, name: form.get("name"), bank_name: form.get("bank_name") || null, account_type: form.get("account_type"), agency: form.get("agency") || null, account_number: form.get("account_number") || null, initial_balance: Number(form.get("initial_balance") || 0), active: true } },
      contact: { table: "contacts", payload: { organization_id, contact_type: form.get("contact_type"), name: form.get("name"), trade_name: form.get("trade_name") || null, document: form.get("document") || null, email: form.get("email") || null, phone: form.get("phone") || null, city: form.get("city") || null, state: form.get("state") || null, notes: form.get("notes") || null, active: true } },
      project: { table: "projects", payload: { organization_id, code: form.get("code"), name: form.get("name"), city: form.get("city") || null, state: form.get("state") || null, status: form.get("status"), total_budget: form.get("total_budget") ? Number(form.get("total_budget")) : null, start_date: form.get("start_date") || null, end_date: form.get("end_date") || null, active: true } },
    };
    await mutate(async () => {
      const supabase = getSupabase(); if (!supabase) throw new Error("Supabase indisponível.");
      const selected = config[kind];
      const query = item ? supabase.from(selected.table).update(selected.payload).eq("id", item.id) : supabase.from(selected.table).insert(selected.payload);
      const { error } = await query; if (error) throw new Error(error.message);
    }, item ? "Cadastro atualizado." : "Cadastro criado.");
    close();
  }
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><PanelTitle eyebrow={item ? "EDITAR CADASTRO" : "NOVO CADASTRO"} title={modalTitle(kind)} /><button className="modal-close" type="button" onClick={close}>×</button><MasterFields kind={kind} item={item} /><footer><button type="button" onClick={close}>Cancelar</button><button className="primary">Salvar cadastro</button></footer></form></div>;
}

function MasterFields({ kind, item }: { kind: EntityKind; item?: Entity }) {
  if (kind === "center") { const value = item as CostCenter | undefined; return <div className="form-grid"><label>Código<input name="code" defaultValue={value?.code} required /></label><label>Tipo<select name="center_type" defaultValue={value?.center_type || "departamento"}><option value="corporativo">Corporativo</option><option value="departamento">Departamento</option><option value="empreendimento">Empreendimento</option><option value="obra">Obra</option><option value="projeto">Projeto</option></select></label><label className="span-2">Nome<input name="name" defaultValue={value?.name} required /></label><label className="span-2">Orçamento<CurrencyInput name="budget" defaultValue={Number(value?.budget || 0)} /></label></div>; }
  if (kind === "revenue") { const value = item as RevenueCenter | undefined; return <div className="form-grid"><label>Código<input name="code" defaultValue={value?.code || ""} required /></label><label>Tipo<select name="center_type" defaultValue={value?.center_type || "recebimento"}><option value="recebimento">Recebimento</option><option value="produto">Produto</option><option value="empreendimento">Empreendimento</option><option value="canal">Canal</option><option value="contrato">Contrato</option><option value="outros">Outros</option></select></label><label className="span-2">Nome<input name="name" defaultValue={value?.name} required /></label><label className="span-2">Meta de recebimento<CurrencyInput name="revenue_goal" defaultValue={Number(value?.revenue_goal || 0)} /></label></div>; }
  if (kind === "category") { const value = item as Category | undefined; return <div className="form-grid"><label>Código<input name="code" defaultValue={value?.code} required /></label><label>Movimento<select name="movement_type" defaultValue={value?.movement_type || "saida"}><option value="entrada">Entrada</option><option value="saida">Saída</option><option value="ambos">Ambos</option></select></label><label className="span-2">Nome<input name="name" defaultValue={value?.name} required /></label></div>; }
  if (kind === "account") { const value = item as BankAccount | undefined; return <div className="form-grid"><label className="span-2">Nome da conta<input name="name" defaultValue={value?.name} required /></label><label>Banco<input name="bank_name" defaultValue={value?.bank_name || ""} /></label><label>Tipo<select name="account_type" defaultValue={value?.account_type || "corrente"}><option value="corrente">Conta corrente</option><option value="poupanca">Poupança</option><option value="caixa">Caixa</option><option value="investimento">Investimento</option><option value="cartao">Cartão</option></select></label><label>Agência<input name="agency" defaultValue={value?.agency || ""} /></label><label>Conta<input name="account_number" defaultValue={value?.account_number || ""} /></label><label className="span-2">Saldo inicial<CurrencyInput name="initial_balance" defaultValue={Number(value?.initial_balance || 0)} /></label></div>; }
  if (kind === "contact") { const value = item as Contact | undefined; return <div className="form-grid"><label>Tipo<select name="contact_type" defaultValue={value?.contact_type || "fornecedor"}><option value="cliente">Cliente</option><option value="fornecedor">Fornecedor</option><option value="ambos">Cliente e fornecedor</option><option value="colaborador">Colaborador</option><option value="corretor">Corretor</option></select></label><label>CPF / CNPJ<input name="document" defaultValue={value?.document || ""} /></label><label className="span-2">Nome / Razão social<input name="name" defaultValue={value?.name} required /></label><label className="span-2">Nome fantasia<input name="trade_name" defaultValue={value?.trade_name || ""} /></label><label>E-mail<input name="email" type="email" defaultValue={value?.email || ""} /></label><label>Telefone<input name="phone" defaultValue={value?.phone || ""} /></label><label>Cidade<input name="city" defaultValue={value?.city || ""} /></label><label>UF<input name="state" maxLength={2} defaultValue={value?.state || ""} /></label><label className="span-2">Observações<textarea name="notes" rows={3} defaultValue={value?.notes || ""} /></label></div>; }
  const value = item as Project | undefined;
  return <div className="form-grid"><label>Código<input name="code" defaultValue={value?.code} required /></label><label>Status<select name="status" defaultValue={value?.status || "planejamento"}><option value="planejamento">Planejamento</option><option value="aprovacao">Aprovação</option><option value="implantacao">Implantação</option><option value="vendas">Vendas</option><option value="concluido">Concluído</option><option value="suspenso">Suspenso</option></select></label><label className="span-2">Nome<input name="name" defaultValue={value?.name} required /></label><label>Cidade<input name="city" defaultValue={value?.city || ""} /></label><label>UF<input name="state" maxLength={2} defaultValue={value?.state || ""} /></label><label>Orçamento total<CurrencyInput name="total_budget" defaultValue={Number(value?.total_budget || 0)} /></label><label>Data inicial<input name="start_date" type="date" defaultValue={value?.start_date || ""} /></label><label className="span-2">Data final<input name="end_date" type="date" defaultValue={value?.end_date || ""} /></label></div>;
}

const modalTitle = (kind: EntityKind) => ({ center: "Centro de custo", revenue: "Centro de recebimento", category: "Categoria financeira", account: "Conta financeira", contact: "Cliente ou fornecedor", project: "Empreendimento ou projeto" } as Record<EntityKind, string>)[kind];
