"use client";

import { useMemo, useState } from "react";
import type { ErpData, FinancialEntry, ViewId } from "./types";
import { aggregateCounterparties, overdueRecommendation, realizedBalance } from "./analytics";
import { buildComprehensiveForecast, operationalCommitments } from "./operational-cash";
import { dateAtNoon, daysUntil, isSettled, money, shortDate, sumEntries } from "./utils";

export function DashboardView({ data, go }: { data: ErpData; go: (view: ViewId) => void }) {
  const receivable = sumEntries(data.entries, "entrada", false);
  const payable = sumEntries(data.entries, "saida", false);
  const overdueIncoming = data.entries.filter(entry => entry.type === "entrada" && !isSettled(entry) && entry.status !== "cancelado" && daysUntil(entry.due_date) < 0);
  const overdueOutgoing = data.entries.filter(entry => entry.type === "saida" && !isSettled(entry) && entry.status !== "cancelado" && daysUntil(entry.due_date) < 0);
  const pendingApprovals = data.approvals.filter(item => item.status === "pendente");
  const pendingPurchases = data.purchaseRequests.filter(item => item.status === "submetida");
  const cashRisks = data.entries.filter(entry => entry.cash_risk && !isSettled(entry) && entry.status !== "cancelado").length + data.purchaseRequests.filter(item => item.cash_risk && !["rejeitada", "cancelada"].includes(item.status)).length + data.hrPayrollRuns.filter(item => item.cash_risk && !["paga", "cancelada"].includes(item.status)).length;
  const upcoming = data.entries.filter(entry => !isSettled(entry) && entry.status !== "cancelado").sort((a, b) => a.due_date.localeCompare(b.due_date)).slice(0, 7);
  const forecast = useMemo(() => buildComprehensiveForecast(data, 90), [data]);
  const sampledForecast = forecast.filter((_point, index) => index % 7 === 0 || index === forecast.length - 1);
  const minForecast = forecast.reduce((min, point) => Math.min(min, point.balance), forecast[0]?.balance ?? 0);
  const negativeDays = forecast.filter(point => point.balance < Number(data.settings.minimum_cash_buffer || 0)).length;
  const debtors = useMemo(() => aggregateCounterparties(data, "entrada").slice(0, 5), [data]);
  const creditors = useMemo(() => aggregateCounterparties(data, "saida").slice(0, 5), [data]);
  const delinquencyRate = receivable ? overdueIncoming.reduce((sum, entry) => sum + Number(entry.amount), 0) / receivable * 100 : 0;
  const operational90 = operationalCommitments(data).filter(item => daysUntil(item.date) <= 90).reduce((sum, item) => sum + item.amount, 0);
  const byProject = useMemo(() => data.projects.map(project => ({ project, incoming: data.entries.filter(entry => entry.project_id === project.id && entry.type === "entrada").reduce((sum, entry) => sum + Number(entry.amount), 0), outgoing: data.entries.filter(entry => entry.project_id === project.id && entry.type === "saida").reduce((sum, entry) => sum + Number(entry.amount), 0) })).filter(item => item.incoming || item.outgoing).sort((a, b) => (b.incoming + b.outgoing) - (a.incoming + a.outgoing)).slice(0, 5), [data]);

  return <div className="dashboard-grid executive-dashboard">
    <section className="executive-card executive-card-v3"><div><small>POSIÇÃO CONSOLIDADA</small><h2>Caixa realizado e projeção de 90 dias</h2><strong>{money.format(realizedBalance(data))}</strong><p>Inclui financeiro, compras aprovadas, folha e eventos de RH previstos.</p><div className="executive-chips"><span>Projetado: <b>{money.format(forecast.at(-1)?.balance ?? 0)}</b></span><span>Compras e RH: <b>{money.format(operational90)}</b></span><span className={negativeDays ? "danger" : "safe"}>Dias abaixo do mínimo: <b>{negativeDays}</b></span></div></div><button onClick={() => go("caixa")}>Abrir análise de caixa →</button></section>
    <section className="kpi-grid six"><Kpi label="A receber" value={money.format(receivable)} tone="positive" detail={`${data.entries.filter(entry => entry.type === "entrada" && !isSettled(entry)).length} títulos`} /><Kpi label="A pagar" value={money.format(payable)} tone="negative" detail={`${data.entries.filter(entry => entry.type === "saida" && !isSettled(entry)).length} títulos`} /><Kpi label="Recebimentos vencidos" value={money.format(overdueIncoming.reduce((sum, entry) => sum + Number(entry.amount), 0))} tone="warning" detail={`${delinquencyRate.toFixed(1)}% da carteira aberta`} /><Kpi label="Pagamentos vencidos" value={money.format(overdueOutgoing.reduce((sum, entry) => sum + Number(entry.amount), 0))} tone="danger" detail={`${overdueOutgoing.length} compromissos`} /><Kpi label="Menor saldo projetado" value={money.format(minForecast)} tone={minForecast < 0 ? "danger" : "gold"} detail="Horizonte de 90 dias" /><Kpi label="Aprovações" value={String(pendingApprovals.length + pendingPurchases.length)} tone="gold" detail={`${cashRisks} com risco de caixa`} /></section>
    <section className="panel span-2"><PanelTitle eyebrow="PREVISIBILIDADE" title="Curva de caixa projetada" action="Detalhar fluxo" onAction={() => go("caixa")} /><div className="forecast-chart">{sampledForecast.map(point => <article key={point.date} className={point.balance < Number(data.settings.minimum_cash_buffer || 0) ? "negative" : "positive"}><b style={{ height: `${Math.max(8, Math.min(100, 50 + point.balance / Math.max(Math.abs(minForecast), Math.abs(forecast.at(-1)?.balance || 1), 1) * 45))}%` }} /><span>{shortDate.format(dateAtNoon(point.date)).slice(0, 5)}</span><small>{money.format(point.balance)}</small></article>)}</div></section>
    <section className="panel span-2"><PanelTitle eyebrow="AGENDA FINANCEIRA" title="Próximos vencimentos" action="Ver lançamentos" onAction={() => go("financeiro")} /><div className="table-list">{upcoming.map(entry => <EntryRow key={entry.id} entry={entry} data={data} />)}{!upcoming.length && <Empty text="Nenhum compromisso pendente." />}</div></section>
    <CounterpartyPanel title="Principais devedores" eyebrow="CONTAS A RECEBER" rows={debtors} empty="Nenhuma carteira de clientes aberta." />
    <CounterpartyPanel title="Principais credores" eyebrow="CONTAS A PAGAR" rows={creditors} empty="Nenhuma obrigação com fornecedores aberta." />
    <section className="panel"><PanelTitle eyebrow="PORTFÓLIO" title="Resultado por empreendimento" /><div className="portfolio-ranking">{byProject.map(({ project, incoming, outgoing }) => <article key={project.id}><div><strong>{project.name}</strong><small>{project.code} · {project.status}</small></div><span><b>{money.format(incoming - outgoing)}</b><small>{money.format(incoming)} entradas · {money.format(outgoing)} saídas</small></span></article>)}{!byProject.length && <Empty text="Sem movimentos por empreendimento." />}</div></section>
    <section className="panel"><PanelTitle eyebrow="GOVERNANÇA" title="Atenções da diretoria" /><div className="attention-list"><button onClick={() => go("aprovacoes")}><b>{pendingApprovals.length}</b><span><strong>Aprovações financeiras</strong><small>Movimentos aguardando decisão</small></span>›</button><button onClick={() => go("compras")}><b>{pendingPurchases.length}</b><span><strong>Compras aguardando aprovação</strong><small>Materiais e serviços solicitados</small></span>›</button><button onClick={() => go("rh")}><b>{data.hrPayrollRuns.filter(item => item.status === "calculada").length}</b><span><strong>Folhas para aprovação</strong><small>Impacto de pessoal no caixa</small></span>›</button></div></section>
    {(overdueIncoming[0] || overdueOutgoing[0]) && <section className="panel span-2 recommendation-panel"><PanelTitle eyebrow="RECOMENDAÇÃO OPERACIONAL" title="Próxima ação sugerida" /><div><strong>{(overdueIncoming[0] || overdueOutgoing[0]).description}</strong><p>{overdueRecommendation(overdueIncoming[0] || overdueOutgoing[0])}</p></div></section>}
  </div>;
}

export function CashView({ data }: { data: ErpData }) {
  const [period, setPeriod] = useState(30);
  const forecast = useMemo(() => buildComprehensiveForecast(data, period), [data, period]);
  const final = forecast.at(-1)?.balance ?? realizedBalance(data);
  const minimum = forecast.reduce((value, point) => Math.min(value, point.balance), forecast[0]?.balance ?? 0);
  const firstNegative = forecast.find(point => point.balance < Number(data.settings.minimum_cash_buffer || 0));
  const incoming = data.entries.filter(entry => !isSettled(entry) && entry.type === "entrada" && daysUntil(entry.due_date) <= period).reduce((sum, entry) => sum + Number(entry.amount), 0);
  const financialOutgoing = data.entries.filter(entry => !isSettled(entry) && entry.type === "saida" && daysUntil(entry.due_date) <= period).reduce((sum, entry) => sum + Number(entry.amount), 0);
  const operational = operationalCommitments(data).filter(item => daysUntil(item.date) <= period).reduce((sum, item) => sum + item.amount, 0);
  const totalOutgoing = financialOutgoing + operational;
  const sample = forecast.filter((_point, index) => index % Math.max(1, Math.round(period / 12)) === 0 || index === forecast.length - 1);
  return <div className="stack"><section className="cash-hero"><div><small>FLUXO PROJETADO · {period} DIAS</small><strong>{money.format(final)}</strong><p>Saldo previsto com financeiro, compras, serviços e RH.</p></div><div>{[7, 15, 30, 90, 180, 365].map(value => <button className={period === value ? "active" : ""} key={value} onClick={() => setPeriod(value)}>{value} dias</button>)}</div></section><section className="kpi-grid five"><Kpi label="Entradas previstas" value={money.format(incoming)} tone="positive" detail="Carteira no período" /><Kpi label="Saídas financeiras" value={money.format(financialOutgoing)} tone="negative" detail="Títulos a pagar" /><Kpi label="Compras e RH" value={money.format(operational)} tone="warning" detail="Compromissos operacionais" /><Kpi label="Menor saldo" value={money.format(minimum)} tone={minimum < 0 ? "danger" : "gold"} detail={firstNegative ? `Risco em ${shortDate.format(dateAtNoon(firstNegative.date))}` : "Sem ruptura projetada"} /><Kpi label="Cobertura" value={totalOutgoing ? `${Math.round(incoming / totalOutgoing * 100)}%` : "—"} tone="gold" detail="Entradas / saídas totais" /></section><section className="panel"><PanelTitle eyebrow="CURVA DIÁRIA" title="Evolução projetada do saldo" /><div className="cash-line-chart">{sample.map(point => <article key={point.date} className={point.balance < Number(data.settings.minimum_cash_buffer || 0) ? "negative" : "positive"}><span>{shortDate.format(dateAtNoon(point.date)).slice(0, 5)}</span><i><b style={{ width: `${Math.max(3, Math.min(100, 50 + point.balance / Math.max(Math.abs(minimum), Math.abs(final), 1) * 48))}%` }} /></i><strong>{money.format(point.balance)}</strong></article>)}</div></section>{firstNegative && <section className="cash-warning"><b>!</b><div><strong>Ruptura de caixa projetada</strong><p>O saldo ficará abaixo do mínimo configurado em {shortDate.format(dateAtNoon(firstNegative.date))}. Reprograme pagamentos, antecipe recebíveis ou submeta a exceção à administração.</p></div></section>}<section className="panel"><PanelTitle eyebrow="DISPONIBILIDADE" title="Saldos por conta" /><div className="account-grid">{data.bankAccounts.map(account => <article key={account.id}><small>{account.bank_name || account.account_type}</small><h3>{account.name}</h3><strong>{money.format(realizedBalance(data, account.id))}</strong><span>Saldo calculado</span></article>)}</div></section></div>;
}

function CounterpartyPanel({ title, eyebrow, rows, empty }: { title: string; eyebrow: string; rows: ReturnType<typeof aggregateCounterparties>; empty: string }) { return <section className="panel"><PanelTitle eyebrow={eyebrow} title={title} /><div className="counterparty-ranking">{rows.map((row, index) => <article key={row.contactId}><b>{index + 1}</b><div><strong>{row.name}</strong><small>{row.titles} títulos · maior atraso {row.oldestDelay} dias</small></div><span><strong>{money.format(row.open)}</strong><small className={row.overdue ? "late" : ""}>{row.overdue ? `${money.format(row.overdue)} vencidos` : "Em dia"}</small></span></article>)}{!rows.length && <Empty text={empty} />}</div></section>; }
export function PanelTitle({ eyebrow, title, action, onAction }: { eyebrow: string; title: string; action?: string; onAction?: () => void }) { return <div className="panel-title"><div><small>{eyebrow}</small><h3>{title}</h3></div>{action && <button onClick={onAction}>{action}</button>}</div>; }
export function Kpi({ label, value, detail, tone = "" }: { label: string; value: string; detail: string; tone?: string }) { return <article className={`kpi ${tone}`}><small>{label}</small><strong>{value}</strong><span>{detail}</span></article>; }
export function Empty({ text }: { text: string }) { return <div className="empty"><b>◇</b><strong>{text}</strong></div>; }
function EntryRow({ entry, data }: { entry: FinancialEntry; data: ErpData }) { const category = data.categories.find(item => item.id === entry.category_id); const late = daysUntil(entry.due_date) < 0; return <article className="entry-row"><i className={entry.type}>{entry.type === "entrada" ? "↓" : "↑"}</i><div><strong>{entry.description}</strong><small>{category?.name || entry.category} · {data.contacts.find(contact => contact.id === entry.contact_id)?.name || "Sem contraparte"}</small></div><span className={late ? "late" : ""}>{shortDate.format(dateAtNoon(entry.due_date))}</span><b className={entry.type}>{entry.type === "saida" ? "−" : "+"}{money.format(Number(entry.amount))}</b></article>; }
