"use client";

import { FormEvent } from "react";
import { getSupabase } from "@/lib/supabase";
import type { ErpData, HrEmployee } from "../types";
import { CurrencyInput } from "../currency-input";
import { PanelTitle } from "../views-dashboard";

export function EmployeeModal({ data, employee, close, mutate }: { data: ErpData; employee: HrEmployee | null; close: () => void; mutate: (operation: () => Promise<void>, success: string) => Promise<void> }) {
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const payload = { organization_id: data.organization.id, full_name: String(form.get("full_name")), document: String(form.get("document") || "") || null, registration_number: String(form.get("registration_number") || "") || null, email: String(form.get("email") || "") || null, phone: String(form.get("phone") || "") || null, job_title: String(form.get("job_title") || "") || null, department: String(form.get("department") || "") || null, cost_center_id: String(form.get("cost_center_id") || "") || null, admission_date: String(form.get("admission_date")), employment_type: String(form.get("employment_type")), base_salary: Number(form.get("base_salary_value") || 0), employer_charge_rate: Number(form.get("employer_charge_rate") || 0) / 100, benefits_monthly: Number(form.get("benefits_value") || 0), active: true, notes: String(form.get("notes") || "") || null };
    await mutate(async () => { const client = getSupabase(); if (!client) throw new Error("Supabase indisponível."); const result = employee ? await client.from("hr_employees").update(payload).eq("id", employee.id) : await client.from("hr_employees").insert(payload); if (result.error) throw new Error(result.error.message); }, employee ? "Colaborador atualizado." : "Colaborador cadastrado."); close();
  }
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal large" onSubmit={submit} onMouseDown={event => event.stopPropagation()}><PanelTitle eyebrow={employee ? "EDITAR COLABORADOR" : "NOVO COLABORADOR"} title={employee?.full_name || "Cadastro de pessoal"} /><button className="modal-close" type="button" onClick={close}>×</button><div className="form-grid three"><label className="span-2">Nome completo<input name="full_name" defaultValue={employee?.full_name} required /></label><label>Matrícula<input name="registration_number" defaultValue={employee?.registration_number || ""} /></label><label>CPF / CNPJ<input name="document" defaultValue={employee?.document || ""} /></label><label>E-mail<input name="email" type="email" defaultValue={employee?.email || ""} /></label><label>Telefone<input name="phone" defaultValue={employee?.phone || ""} /></label><label>Cargo<input name="job_title" defaultValue={employee?.job_title || ""} /></label><label>Departamento<input name="department" defaultValue={employee?.department || ""} /></label><label>Centro de custo<select name="cost_center_id" defaultValue={employee?.cost_center_id || ""}><option value="">Selecione</option>{data.costCenters.filter(item => item.active).map(item => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Admissão<input name="admission_date" type="date" defaultValue={employee?.admission_date || new Date().toISOString().slice(0, 10)} required /></label><label>Vínculo<select name="employment_type" defaultValue={employee?.employment_type || "clt"}><option value="clt">CLT</option><option value="pj">Pessoa jurídica</option><option value="estagio">Estágio</option><option value="temporario">Temporário</option><option value="diretor">Diretor</option></select></label><label>Salário / remuneração<CurrencyInput name="base_salary" defaultValue={employee?.base_salary || 0} /><input type="hidden" name="base_salary_value" value={employee?.base_salary || 0} /></label><label>Encargos estimados (%)<input name="employer_charge_rate" type="number" step="0.01" defaultValue={Number(employee?.employer_charge_rate || data.settings.default_employer_charge_rate || 0) * 100} /></label><label>Benefícios mensais<CurrencyInput name="benefits" defaultValue={employee?.benefits_monthly || 0} /><input type="hidden" name="benefits_value" value={employee?.benefits_monthly || 0} /></label><label className="span-3">Observações<textarea name="notes" rows={3} defaultValue={employee?.notes || ""} /></label></div><footer><button type="button" onClick={close}>Cancelar</button><button className="primary">Salvar colaborador</button></footer></form></div>;
}
