"use client";
import {FormEvent,useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import type {ErpData,DocumentAttachment} from "../types";

type LinkItem={id:string;title:string;url:string;notes:string|null;created_at:string};
const safe=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-100);

export function CommunicationResources({data,entityType,entityId}:{data:ErpData;entityType:string;entityId:string}){
 const[files,setFiles]=useState<DocumentAttachment[]>([]),[links,setLinks]=useState<LinkItem[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const s=getSupabase();if(!s)return;const[f,l]=await Promise.all([s.from("document_attachments").select("*").eq("organization_id",data.organization.id).eq("entity_type",entityType).eq("entity_id",entityId).order("created_at",{ascending:false}),s.from("communication_links").select("*").eq("organization_id",data.organization.id).eq("entity_type",entityType).eq("entity_id",entityId).order("created_at",{ascending:false})]);if(f.error||l.error)setError(f.error?.message||l.error?.message||"");else{setFiles((f.data||[]) as DocumentAttachment[]);setLinks((l.data||[]) as LinkItem[])}}
 useEffect(()=>{load()},[entityId]);
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const form=new FormData(e.currentTarget),file=form.get("file") as File;if(!file?.size)throw new Error("Selecione um arquivo");const max=Number(data.settings.document_max_size_mb||20)*1024*1024;if(file.size>max)throw new Error(`O arquivo supera ${data.settings.document_max_size_mb||20} MB`);const s=getSupabase();if(!s)throw new Error("Supabase indisponível");const path=`${data.organization.id}/${entityType}/${entityId}/${crypto.randomUUID()}-${safe(file.name)}`;const up=await s.storage.from("erp-documents").upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const meta=await s.from("document_attachments").insert({organization_id:data.organization.id,entity_type:entityType,entity_id:entityId,document_type:"comunicacao",file_name:file.name,storage_path:path,mime_type:file.type||null,size_bytes:file.size,notes:String(form.get("notes")||"")||null,uploaded_by:data.session.user.id});if(meta.error){await s.storage.from("erp-documents").remove([path]);throw meta.error}e.currentTarget.reset();await load()}catch(err){setError(err instanceof Error?err.message:"Não foi possível anexar") }finally{setBusy(false)}}
 async function addLink(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const form=new FormData(e.currentTarget),raw=String(form.get("url")||"").trim();const url=new URL(raw).toString();const s=getSupabase();if(!s)throw new Error("Supabase indisponível");const r=await s.from("communication_links").insert({organization_id:data.organization.id,entity_type:entityType,entity_id:entityId,title:String(form.get("title")||"Link"),url,notes:String(form.get("notes")||"")||null,created_by:data.session.user.id});if(r.error)throw r.error;e.currentTarget.reset();await load()}catch(err){setError(err instanceof Error?err.message:"Link inválido") }finally{setBusy(false)}}
 async function openFile(item:DocumentAttachment){const s=getSupabase();if(!s)return;const r=await s.storage.from("erp-documents").createSignedUrl(item.storage_path,180);if(r.data?.signedUrl)window.open(r.data.signedUrl,"_blank","noopener,noreferrer");else setError(r.error?.message||"Não foi possível abrir")}
 return <section className="communication-resources"><header><div><small>ANEXOS E LINKS</small><h4>Materiais da comunicação</h4></div><span>{files.length+links.length} item(ns)</span></header><div className="communication-resource-forms"><form onSubmit={upload}><label>Arquivo<input name="file" type="file" required/></label><label>Observação<input name="notes"/></label><button className="primary" disabled={busy}>Anexar arquivo</button></form><form onSubmit={addLink}><label>Título<input name="title" required/></label><label>Link<input name="url" type="url" placeholder="https://" required/></label><label>Observação<input name="notes"/></label><button className="primary" disabled={busy}>Adicionar link</button></form></div>{error&&<div className="feedback error">{error}</div>}<div className="communication-resource-list">{files.map(f=><button key={f.id} type="button" onClick={()=>openFile(f)}><b>▧</b><span>{f.file_name}<small>{f.notes||"Arquivo anexado"}</small></span></button>)}{links.map(l=><a key={l.id} href={l.url} target="_blank" rel="noreferrer"><b>↗</b><span>{l.title}<small>{l.notes||l.url}</small></span></a>)}</div></section>}
