"use client";
import {useMemo,useState} from "react";
import type {ConstructionWorkPackage,ErpData} from "../types";
import {money,shortDate,dateAtNoon} from "../utils";
import {Empty,Kpi,PanelTitle} from "../views-dashboard";

const clamp=(value:number,min=0,max=100)=>Math.max(min,Math.min(max,value));
const weighted=(rows:ConstructionWorkPackage[],key:"planned_progress"|"actual_progress")=>{const executable=rows.filter(row=>!row.is_summary);const total=executable.reduce((sum,row)=>sum+Math.max(Number(row.weight_pct)||0,0),0);if(!executable.length)return 0;if(total<=0)return executable.reduce((sum,row)=>sum+Number(row[key]||0),0)/executable.length;return executable.reduce((sum,row)=>sum+Number(row[key]||0)*Math.max(Number(row.weight_pct)||0,0),0)/total};

function HealthGauge({score,actual,planned}:{score:number;actual:number;planned:number}){
 const angle=-90+(clamp(score)*1.8),r=82,cx=110,cy=105,x=cx+Math.cos(angle*Math.PI/180)*r,y=cy+Math.sin(angle*Math.PI/180)*r;
 const tone=score>=80?"Saudável":score>=65?"Atenção":score>=45?"Risco":"Crítico";
 return <div className={`construction-gauge score-${score>=80?"good":score>=65?"attention":score>=45?"risk":"critical"}`}><svg viewBox="0 0 220 132" role="img" aria-label={`Saúde da obra ${Math.round(score)} de 100`}><path className="gauge-track" d="M28 105 A82 82 0 0 1 192 105"/><path className="gauge-zone green" d="M28 105 A82 82 0 0 1 76 38"/><path className="gauge-zone yellow" d="M76 38 A82 82 0 0 1 123 24"/><path className="gauge-zone orange" d="M123 24 A82 82 0 0 1 169 53"/><path className="gauge-zone red" d="M169 53 A82 82 0 0 1 192 105"/><line className="gauge-needle" x1={cx} y1={cy} x2={x} y2={y}/><circle className="gauge-center" cx={cx} cy={cy} r="7"/></svg><div className="gauge-reading"><strong>{Math.round(score)}</strong><span>/100</span><b>{tone}</b><small>{actual.toFixed(1)}% realizado · {planned.toFixed(1)}% previsto</small></div></div>;
}

function ProgressPair({planned,actual}:{planned:number;actual:number}){const variance=actual-planned;return <div className="eap-progress"><div className="eap-progress-line actual"><span>Realizado</span><i><b style={{width:`${clamp(actual)}%`}}/></i><strong>{actual.toFixed(0)}%</strong></div><div className="eap-progress-line planned"><span>Previsto</span><i><b style={{width:`${clamp(planned)}%`}}/></i><strong>{planned.toFixed(0)}%</strong></div><small className={variance<-10?"late":variance<0?"attention":"ok"}>Desvio {variance>=0?"+":""}{variance.toFixed(0)} p.p.</small></div>}

export function ConstructionManagementView({data}:{data:ErpData}){
 const projectsWithPackages=useMemo(()=>data.projects.filter(project=>data.constructionWorkPackages.some(row=>row.project_id===project.id)),[data.projects,data.constructionWorkPackages]);
 const[projectId,setProjectId]=useState(projectsWithPackages[0]?.id||data.projects[0]?.id||"");
 const rows=useMemo(()=>data.constructionWorkPackages.filter(row=>row.project_id===projectId),[data.constructionWorkPackages,projectId]);
 const executable=rows.filter(row=>!row.is_summary),actual=weighted(rows,"actual_progress"),planned=weighted(rows,"planned_progress"),variance=actual-planned;
 const budget=executable.reduce((sum,row)=>sum+Number(row.budget_amount||0),0),committed=executable.reduce((sum,row)=>sum+Number(row.committed_amount||0),0);
 const risks=data.constructionRisks.filter(row=>row.project_id===projectId&&!['encerrado','mitigado','cancelado'].includes(row.status)),criticalRisks=risks.filter(row=>Number(row.score)>=16).length;
 const hseq=data.constructionHseqRecords.filter(row=>row.project_id===projectId&&!['encerrado','verificado','cancelado'].includes(row.status)),criticalHseq=hseq.filter(row=>['critica','crítica','alta'].includes((row.severity||'').toLowerCase())).length;
 const scheduleScore=clamp(100-Math.max(0,-variance)*2),costRatio=budget>0?committed/budget:0,costScore=costRatio<=1?100:clamp(100-(costRatio-1)*160),riskScore=clamp(100-criticalRisks*15-criticalHseq*12-risks.length*2-hseq.length),health=clamp(scheduleScore*.55+costScore*.25+riskScore*.20);
 const snapshots=data.constructionProgressSnapshots.filter(row=>row.project_id===projectId&&!row.work_package_id).slice(-12);
 return <div className="stack construction-module"><section className="construction-hero"><div><small>PLANEJAMENTO · CAMPO · CUSTO · QUALIDADE</small><h2>Comando inteligente da obra</h2><p>Avanço físico, saúde do cronograma, riscos e custo em uma leitura executiva.</p></div><select value={projectId} onChange={event=>setProjectId(event.target.value)}>{data.projects.map(project=><option value={project.id} key={project.id}>{project.code} · {project.name}</option>)}</select></section><section className="construction-command-grid"><article className="construction-health-card"><small>ÍNDICE DE SAÚDE DA OBRA</small><HealthGauge score={health} actual={actual} planned={planned}/></article><div className="construction-kpi-stack"><Kpi label="Avanço físico" value={`${actual.toFixed(1)}%`} detail={`Linha de base: ${planned.toFixed(1)}%`} tone={variance<-10?"danger":variance<0?"warning":"positive"}/><Kpi label="Orçamento da obra" value={money.format(budget)} detail={`${money.format(committed)} comprometidos`} tone={costRatio>1?"danger":"gold"}/><Kpi label="Riscos abertos" value={String(risks.length+hseq.length)} detail={`${criticalRisks+criticalHseq} críticos ou altos`} tone={criticalRisks+criticalHseq?"danger":"positive"}/></div></section>{snapshots.length>1&&<section className="panel"><PanelTitle eyebrow="TENDÊNCIA" title="Evolução física da obra"/><div className="construction-trend">{snapshots.map(row=><article key={row.id}><span>{shortDate.format(dateAtNoon(row.reference_date)).slice(0,5)}</span><i><b style={{height:`${clamp(Number(row.actual_progress))}%`}}/></i><small>{Number(row.actual_progress).toFixed(0)}%</small></article>)}</div></section>}<section className="panel"><PanelTitle eyebrow="EAP · LINHA DE BASE" title="Pacotes de trabalho e percentual da etapa"/><div className="eap-table"><div className="eap-table-head"><span>Código / pacote</span><span>Período</span><span>Avanço</span><span>Orçamento</span></div>{rows.map(row=><article className={row.is_summary?"summary":""} key={row.id}><div><small>{row.wbs_code||row.package_code}</small><strong>{row.name}</strong><span>{row.phase||row.discipline||row.status}</span></div><div><span>{row.planned_start?shortDate.format(dateAtNoon(row.planned_start)):"—"} → {row.planned_end?shortDate.format(dateAtNoon(row.planned_end)):"—"}</span></div><ProgressPair planned={Number(row.planned_progress||0)} actual={Number(row.actual_progress||0)}/><div><strong>{row.is_summary?"Consolidador":money.format(Number(row.budget_amount||0))}</strong><span>{row.is_summary?"sem duplicar valores":`${money.format(Number(row.committed_amount||0))} comprometidos`}</span></div></article>)}{!rows.length&&<Empty text="Nenhum pacote da EAP cadastrado para este empreendimento."/>}</div></section></div>;
}
