import {createClient} from "@supabase/supabase-js";
import {NextRequest,NextResponse} from "next/server";
import {createHash,randomInt} from "crypto";
export const runtime="nodejs";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://qsdffayasuzsmngteika.supabase.co";
function admin(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error("Chave administrativa do Supabase não configurada.");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function normalizePhone(value:string){const digits=value.replace(/\D/g,"");return digits.startsWith("55")?digits:`55${digits}`}
export async function POST(req:NextRequest){try{const body=await req.json();const token=String(body.token||"");const entityType=body.entityType==="proposal"?"proposal":"contract";if(!token)throw new Error("Link inválido.");const db=admin();const rpc=entityType==="contract"?"crm_get_public_contract":"crm_get_public_proposal_snapshot";const{data,error}=await db.rpc(rpc,{p_token:token});if(error||!data)throw new Error("Documento inválido ou expirado.");const entity=entityType==="contract"?data.contract:data.proposal;const entityId=entity?.id;const organizationId=data.organization_id||entity?.organization_id;const rawPhone=data.proposal?.customer_phone||data.customer?.phone||data.proposal?.phone;if(!entityId||!organizationId||!rawPhone)throw new Error("Telefone do cliente não cadastrado.");const phone=normalizePhone(String(rawPhone));const code=String(randomInt(100000,1000000));const salt=createHash("sha256").update(`${code}:${token}:${Date.now()}`).digest("hex").slice(0,16);const hash=`$2a$06$${salt.padEnd(22,"0").slice(0,22)}`;const{data:encrypted,error:cryptError}=await db.rpc("crypt",{password:code,salt:hash});let otpHash=encrypted;if(cryptError||!encrypted){const{data:h,error:hErr}=await db.rpc("gen_salt",{type:"bf",iter_count:6});if(hErr)throw hErr;const{data:c,error:cErr}=await db.rpc("crypt",{password:code,salt:h});if(cErr)throw cErr;otpHash=c}
const{data:challenge,error:insertError}=await db.from("signature_otp_challenges").insert({organization_id:organizationId,entity_type:entityType,entity_id:entityId,public_token:token,phone_masked:`•••• ${phone.slice(-4)}`,otp_hash:otpHash,expires_at:new Date(Date.now()+10*60000).toISOString()}).select("id,phone_masked,expires_at").single();if(insertError)throw insertError;
const accessToken=process.env.WHATSAPP_ACCESS_TOKEN,phoneNumberId=process.env.WHATSAPP_PHONE_NUMBER_ID,template=process.env.WHATSAPP_OTP_TEMPLATE||"evora_codigo_assinatura";if(!accessToken||!phoneNumberId)throw new Error("Integração oficial do WhatsApp ainda não configurada. Cadastre WHATSAPP_ACCESS_TOKEN e WHATSAPP_PHONE_NUMBER_ID na Vercel.");const response=await fetch(`https://graph.facebook.com/v22.0/${phoneNumberId}/messages`,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:phone,type:"template",template:{name:template,language:{code:"pt_BR"},components:[{type:"body",parameters:[{type:"text",text:code}]}]}})});if(!response.ok){const detail=await response.text();throw new Error(`WhatsApp não confirmou o envio: ${detail.slice(0,240)}`)}return NextResponse.json({challengeId:challenge.id,phoneMasked:challenge.phone_masked,expiresAt:challenge.expires_at})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Não foi possível enviar o código."},{status:400})}}