"use client";
import Image from "next/image";
import { SolarisCaptureForm } from "./SolarisCaptureForm";
import { SolarisBookLink } from "./SolarisBookLink";
import { SolarisPartners } from "./SolarisPartners";
import base from "./solaris-form.module.css";
import s from "./solaris-nature.module.css";

const book = "/forms/solaris/book";
const photos = "/forms/solaris/nature";
const leisure = [
  ["Caminhar sem pressa", "Bosques, trilhas e ciclovias para incluir mais movimento e natureza na rotina."],
  ["Encontrar os amigos", "Piscinas adulto e infantil, espaço gourmet e ambientes de convivência."],
  ["Brincar lá fora", "Espaços infantis, brinquedoteca e pet place para a família toda."],
  ["Ter tempo para jogar", "Tênis, beach tennis, futebol society e quadra poliesportiva."],
  ["Cuidar de você", "Academia, spa e sauna previstos na Casa Évora."],
  ["Estar perto dos animais", "A hípica faz parte da proposta de lazer ao ar livre do residencial."],
];
function Brand() { return <span className={s.brand}><Image src={`${book}/simbolo.avif`} width={44} height={46} alt="" unoptimized /><span>SOLARIS<small>RESIDENCIAL RESORT</small></span></span>; }

export function SolarisNature() {
  return <main className={`${base.shell} ${s.page}`} id="conteudo-principal" data-solaris-version="natureza-v1">
    <a className={base.skip} href="#formulario">Ir para o formulário</a>
    <header className={s.header}><a href="#inicio" aria-label="Solaris — início"><Brand /></a><nav aria-label="Conheça o Solaris"><a href="#vizinhos">Seus próximos vizinhos</a><a href="#lazer">Lazer</a><a href="#localizacao">Localização</a></nav><a className={s.button} href="#formulario">Quero conhecer ↗</a></header>
    <section className={s.hero} id="inicio" aria-labelledby="solaris-titulo"><div className={s.heroText}>
      <p className={s.eyebrow}>MONTE CARMELO · MG / LOTES RESIDENCIAIS</p><p className={s.series}>Série · Seus próximos vizinhos</p>
      <h1 id="solaris-titulo">Uma vida mais simples.<br /><em>Mais perto da natureza.</em></h1>
      <p>Ouvir os pássaros. Caminhar no fim da tarde. Ter mais tempo para estar junto. Conheça a proposta do Solaris e imagine esses pequenos momentos na sua rotina.</p>
      <a className={s.button} href="#formulario">Conhecer os lotes →</a><span className={s.note}>Lotes a partir de 360 m² · Obras em andamento</span>
    </div><figure className={s.heroPhoto}><Image src={`${photos}/paisagem.webp`} alt="Vegetação e água entre árvores, iluminadas pelo sol do fim da tarde." width={1536} height={1024} sizes="(max-width: 760px) 100vw, 55vw" unoptimized loading="eager" fetchPriority="high" /><figcaption>Um convite a reparar nas coisas simples.<small>Fotografia do acervo da campanha.</small></figcaption></figure></section>
    <div className={s.facts}><p><strong>Monte Carmelo</strong><span>Parque das Árvores · MG</span></p><p><strong>A partir de 360 m²</strong><span>Lotes para o seu projeto de vida</span></p><p><strong>Lazer e natureza</strong><span>Espaços previstos para compartilhar</span></p></div>
    <section className={s.section} id="vizinhos" aria-labelledby="vizinhos-titulo"><div className={s.intro}><p className={s.eyebrow}>SEUS PRÓXIMOS VIZINHOS</p><h2 id="vizinhos-titulo">A natureza faz parte<br /><em>dessa conversa.</em></h2><p>A campanha começa com quem inspira esse jeito de viver: as aves, o verde, a vida ao ar livre. E continua com o que você procura para a sua família.</p></div>
      <div className={s.birds}><figure><Image src={`${photos}/pica-pau.webp`} alt="Pica-pau-do-campo pousado em um mourão de madeira." width={800} height={1200} sizes="(max-width: 760px) 88vw, 31vw" unoptimized /><figcaption><span>01 / UM ENCONTRO PELO CAMINHO</span><h3>Olhar com mais calma.</h3><p>Às vezes, a melhor parte do dia está nos pequenos detalhes.</p></figcaption></figure><figure><Image src={`${photos}/coruja.webp`} alt="Coruja entre a vegetação, fotografada de perto." width={1000} height={667} sizes="(max-width: 760px) 88vw, 31vw" unoptimized /><figcaption><span>02 / A VIDA ACONTECE LÁ FORA</span><h3>Redescobrir o entorno.</h3><p>Trocar um pouco da correria por mais atenção ao que está perto.</p></figcaption></figure><div className={s.invitation}><span aria-hidden="true">↗</span><h3>Agora só<br />falta você.</h3><p>Um lugar para construir a sua casa e cultivar uma rotina com mais natureza, lazer e convivência.</p><a href="#formulario">Vamos conversar sobre o Solaris →</a></div></div>
      <p className={s.caption}>Fotografias do acervo da campanha. As imagens de natureza não representam estruturas de lazer entregues.</p>
    </section>
    <section className={`${s.section} ${s.leisure}`} id="lazer" aria-labelledby="lazer-titulo"><div className={s.intro}><p className={s.eyebrow}>MAIS TEMPO PARA O QUE FAZ BEM</p><h2 id="lazer-titulo">Lazer para a vida<br /><em>de todos os dias.</em></h2><p>Espaços para descansar, brincar, se movimentar e encontrar quem você gosta. Conheça alguns dos itens previstos no book comercial.</p></div><div className={s.leisureGrid}>{leisure.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className={s.bookLine}><p>Empreendimento em obras. Consulte os itens, o memorial e o cronograma de implantação.</p><SolarisBookLink>Ver o projeto completo (PDF) ↗</SolarisBookLink></div></section>
    <section className={`${s.section} ${s.contact}`} aria-labelledby="contato-titulo"><div className={s.intro}><p className={s.eyebrow}>O PRIMEIRO PASSO É UMA CONVERSA</p><h2 id="contato-titulo">Seu próximo capítulo<br /><em>pode começar aqui.</em></h2><p>Receba informações sobre os lotes, valores e condições. A equipe da Futura Casa entra em contato pelo WhatsApp para entender o que você procura.</p><ul><li>Atendimento para morar ou investir</li><li>Disponibilidade e condições atualizadas</li><li>Cadastro sem compromisso de compra</li></ul><div className={s.service}><span>ATENDIMENTO</span><Image src={`${book}/futura-casa-monocromatica-v1.webp`} alt="Futura Casa — Inteligência Imobiliária, Marketing e Vendas" width={720} height={346} unoptimized /></div></div><SolarisCaptureForm /></section>
    <section className={`${s.section} ${s.location}`} id="localizacao" aria-labelledby="localizacao-titulo"><div className={s.intro}><p className={s.eyebrow}>PERTINHO DA SUA VIDA</p><h2 id="localizacao-titulo">Em Monte Carmelo.<br /><em>No Parque das Árvores.</em></h2><p>O Solaris integra o projeto do bairro Parque das Árvores. Converse com a equipe para conhecer a localização, o acesso e os lotes disponíveis.</p><a className={s.textLink} href="#formulario">Quero conhecer a localização →</a></div><figure><Image src={`${book}/parque-das-arvores-setores.avif`} alt="Mapa ilustrativo dos setores do Parque das Árvores e da localização do Solaris." width={1024} height={683} sizes="(max-width: 760px) 90vw, 44vw" unoptimized /><figcaption>Perspectiva ilustrativa do bairro · Não é uma fotografia das obras.<a href={`${book}/parque-das-arvores-setores.avif`} target="_blank" rel="noopener">Ampliar mapa ↗</a></figcaption></figure></section>
    <section className={`${s.section} ${s.faq}`} aria-labelledby="duvidas-titulo"><h2 id="duvidas-titulo">Antes de dar<br />o próximo passo.</h2><div><details><summary>O Solaris já está pronto para morar?</summary><p>O empreendimento está em obras. Os itens de lazer são previstos em projeto. Confirme o estágio das obras, o memorial descritivo e o cronograma contratual com a equipe.</p></details><details><summary>Qual o tamanho dos lotes?</summary><p>O book apresenta lotes a partir de 360 m². As metragens e unidades disponíveis serão informadas no atendimento.</p></details><details><summary>Como saber valores e formas de pagamento?</summary><p>Deixe seu nome e WhatsApp para receber as condições atuais. O book prevê financiamento com a loteadora; entrada, parcelas, juros, correções e prazos dependem da proposta comercial.</p></details><details><summary>Meu cadastro reserva um lote?</summary><p>Não. Ele registra seu interesse para que a equipe entre em contato. Qualquer reserva ou compra exige uma etapa comercial específica.</p></details></div></section>
    <SolarisPartners /><footer className={s.footer}><Brand /><p>Solaris Residencial Resort · Monte Carmelo, MG</p><p>Informações de projeto baseadas no Book Comercial Solaris 2026 V6. Consulte o memorial descritivo, a documentação contratual e a disponibilidade atual. Fotografias de natureza do acervo da campanha; mapa ilustrativo.</p><a href="/privacidade">Privacidade e uso dos dados</a></footer>
  </main>;
}
